### PR TITLE
modify bench to allow running read benchmarks without filled db

### PR DESCRIPTION
**Pull request by JanDorniak99**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/73)

### CODE REVIEW

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/73)* status: 0 of 3 files reviewed, 2 unresolved discussions (waiting on @JanDorniak99)

___
*[README.md, line 20 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYKGZvQ-KEGZPbDpxIt:-MYKGZvQ-KEGZPbDpxIu:b-x11u15) ([raw file](https://github.com/pmem/pmemkv-bench/blob/c20a1076520370d968f68eca063de36049f51269/README.md#L20)):*
> ```Markdown
> 
> **Note:**
> >It is the user's responsibility to clear/remove DB (e.g. pmempool rm). So running bench with --benchmarks=fillseq,fillrandom
> ```

Please add some link to pmempool rm docs (on pmem.io)
___
*[tests/test.py, line 38 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYKGrrH-XA5QDNyqO7c:-MYKGrrH-XA5QDNyqO7d:b6jlhlh) ([raw file](https://github.com/pmem/pmemkv-bench/blob/c20a1076520370d968f68eca063de36049f51269/tests/test.py#L38)):*
> ```Python
>             "cmap",
>             os.getenv("KV_BENCH_TEST_PATH", "/dev/shm/pmemkv"),
>             "readrandom,fillrandom,readrandom",
> ```

Please extend the tests instead of replacing them, I think it would still be good to have tests which start with fillrandom.

Also, is it possible to run test for fillarandom and then readrandom in separate processes? (ideally we would check that the number of elements read is the same as number of elements written).

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/73)* status: 0 of 4 files reviewed, 2 unresolved discussions (waiting on @igchor)

___
*[README.md, line 20 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYKGZvQ-KEGZPbDpxIt:-MYdK-0t2k943c1SZcQZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/c20a1076520370d968f68eca063de36049f51269/README.md#L20)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please add some link to pmempool rm docs (on pmem.io)
</blockquote></details>

Done.
___
*[tests/test.py, line 38 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYKGrrH-XA5QDNyqO7c:-MYikzNU0AO43v3uADpt:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/c20a1076520370d968f68eca063de36049f51269/tests/test.py#L38)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Please extend the tests instead of replacing them, I think it would still be good to have tests which start with fillrandom.

Also, is it possible to run test for fillarandom and then readrandom in separate processes? (ideally we would check that the number of elements read is the same as number of elements written).
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-:-MYiom_q6KHkJH8j-fVF:bnfp4nl)* status: 0 of 4 files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/73)* status: 0 of 4 files reviewed, 12 unresolved discussions (waiting on @JanDorniak99)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjMECLDJC-OQU6DAF8:-MYjMECLDJC-OQU6DAF9:b-j0wxrd) (no related file):*
in commit messages, perhaps extend:
1. add info why you reverting this
2. mention you remove overwrite benchmark and why 

---
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjRONb3Si-oqi549Nc:-MYjRONb3Si-oqi549Nd:b-a1n0j0) (no related file):*
maybe we could note somewhere in the readme file, how to achieve overwrite benchmark...?

---
___
*[README.md, line 20 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjJOZc-S5VPRGKSVAk:-MYjJOZc-S5VPRGKSVAl:bmdq4o5) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L20)):*
> ```Markdown
> 
> **Note:**
> >It is the user's responsibility to clear/remove DB (e.g. [pmempool rm](https://pmem.io/pmdk/manpages/linux/v1.10/pmempool/pmempool-rm.1.html)).
> ```

`e.g. using [pmempool rm] ...`
___
*[README.md, line 21 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjJa202mRoq9ErXx9_:-MYjJa202mRoq9ErXx9a:b1vam89) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L21)):*
> ```Markdown
> **Note:**
> >It is the user's responsibility to clear/remove DB (e.g. [pmempool rm](https://pmem.io/pmdk/manpages/linux/v1.10/pmempool/pmempool-rm.1.html)).
> >So running bench with --benchmarks=fillseq,fillrandom might have another result than running with --benchmarks=fillseq, removing DB and running with --benchmarks--fillrandom,
> ```

put this params into code markdown (\`xxx\`)
___
*[README.md, line 21 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjJz-G5H7DMdPV47OH:-MYjJz-G5H7DMdPV47OI:byaa9xq) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L21)):*
> ```Markdown
> **Note:**
> >It is the user's responsibility to clear/remove DB (e.g. [pmempool rm](https://pmem.io/pmdk/manpages/linux/v1.10/pmempool/pmempool-rm.1.html)).
> >So running bench with --benchmarks=fillseq,fillrandom might have another result than running with --benchmarks=fillseq, removing DB and running with --benchmarks--fillrandom,
> ```

`and running with ...` -> `and running bench once more with ...`
___
*[README.md, line 21 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjK2aX4slcDxpogxAz:-MYjK2aX4slcDxpogxB-:b-16ovlr) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L21)):*
> ```Markdown
> **Note:**
> >It is the user's responsibility to clear/remove DB (e.g. [pmempool rm](https://pmem.io/pmdk/manpages/linux/v1.10/pmempool/pmempool-rm.1.html)).
> >So running bench with --benchmarks=fillseq,fillrandom might have another result than running with --benchmarks=fillseq, removing DB and running with --benchmarks--fillrandom,
> ```

another result -> different result**s**
___
*[README.md, line 22 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjKMik0xTOav6srUqK:-MYjKMik0xTOav6srUqL:b-xzlpra) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L22)):*
> ```Markdown
> >It is the user's responsibility to clear/remove DB (e.g. [pmempool rm](https://pmem.io/pmdk/manpages/linux/v1.10/pmempool/pmempool-rm.1.html)).
> >So running bench with --benchmarks=fillseq,fillrandom might have another result than running with --benchmarks=fillseq, removing DB and running with --benchmarks--fillrandom,
> >because in the first case 'fillrandom' is writing to the already filled DB.
> ```

`is writing` -> `writes`
___
*[README.md, line 41 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjKaks0DD6UpUuSZ6r:-MYjKaks0DD6UpUuSZ6s:b-aty1s9) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L41)):*
> ```Markdown
> * **Linux 64-bit** (OSX and Windows are not yet supported)
> * [**libpmemkv**](https://github.com/pmem/pmemkv) - library tested in this benchmark;
>     currently only version from master branch
> ```

`... is supported`
or
`currently version from master branch is required`
___
*[README.md, line 118 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjL5dLBfAeKjiUaV3W:-MYjL5dLBfAeKjiUaV3X:b-75petw) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L118)):*
> ```Markdown
> 
> **Remember:**
> >The `pmemkv-bench` won't clear the pool passed in `--db` parameter, it is the user's responsibility.
> ```

I'd write it a bit more verbose:
`... parameter on start or at finish. It is ... responsibility to clear it if desired.`
___
*[bench/db_bench.cc, line 578 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjNHoN79TCJ5dHFMbD:-MYjNHoN79TCJ5dHFMbE:b-l0tlm4) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/bench/db_bench.cc#L578)):*
> ```cpp
> 		PrintHeader();
> 
> 		if (!kv_) {
> ```

do we close `kv_` somewhere now?
___
*[tests/test.py, line 145 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjQbF9Ak96UqJG3XqH:-MYjQbF9Ak96UqJG3XqI:bj16itk) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/tests/test.py#L145)):*
> ```Python
>         },
>     ]
>     execute_benchmark(benchmark_configuration)
> ```

perhaps assign this to some variable to see if it contains proper count of results (2 in this case?)
___
*[tests/test.py, line 167 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjPlFT4gxGBFFNHwuS:-MYjPlFT4gxGBFFNHwuT:b-ibmpev) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/tests/test.py#L167)):*
> ```Python
> 
>     execute_benchmark(benchmark_configuration)
> ```

I'll be boring as hell, but perhaps pls add some comments (general one for the test itself and here in the code, to describe what's going on)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/73)* status: 0 of 4 files reviewed, 13 unresolved discussions (waiting on @JanDorniak99)

___
*[tests/test.py, line 147 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjUSNh2Hn-x6LXnJVq:-MYjUSNh2Hn-x6LXnJVr:b-9phteh) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/tests/test.py#L147)):*
> ```Python
>     execute_benchmark(benchmark_configuration)
> ```

add also a test with read-only workload and see if `found == 0`

and perhaps we should have a warning in the bench's code saying that you read nothing...?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/73)* status: 0 of 4 files reviewed, 16 unresolved discussions (waiting on @JanDorniak99)

___
*[bench/db_bench.cc, line 30 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYk3QhQ6DZoS7UALp5r:-MYk3QhQ6DZoS7UALp5s:b-5240gu) ([raw file](https://github.com/pmem/pmemkv-bench/blob/d26c3a18a3a26ea3b184e60adac012667cfb7cb5/bench/db_bench.cc#L30)):*
> ```cpp
> #include "leveldb/env.h"
> #include "libpmemkv.hpp"
> #include "libpmempool.h"
> ```

This include is no more needed
___
*[bench/db_bench.cc, line 1124 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYk43z-8V5g4ECgnVqa:-MYk43z-8V5g4ECgnVqb:bwwzf8) ([raw file](https://github.com/pmem/pmemkv-bench/blob/d26c3a18a3a26ea3b184e60adac012667cfb7cb5/bench/db_bench.cc#L1124)):*
> ```cpp
> 	}
> 	if (kv != NULL) {
> 		kv->close();
> ```

close on exit is probably still needed. 
___
*[tests/test.py, line 173 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYk8Je-E3_obG017T0v:-MYk8Je-E3_obG017T0w:b-ov6m1s) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/tests/test.py#L173)):*
> ```Python
> 
>     extra_data = res[0]["results"][0]["extra_data"]
>     found = int(extra_data.split()[0][1:])
> ```

It would be good, if you add comment with example of data, which  you are parsing.

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/73)* status: 0 of 4 files reviewed, 15 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjMECLDJC-OQU6DAF8:-MYo9Vrc3oxyEYYybwtm:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in commit messages, perhaps extend:
1. add info why you reverting this
2. mention you remove overwrite benchmark and why 
</blockquote></details>

Done.

---
___
*[README.md, line 20 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjJOZc-S5VPRGKSVAk:-MYnvKxz6MBs64s2JW24:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L20)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`e.g. using [pmempool rm] ...`
</blockquote></details>

Done.
___
*[README.md, line 21 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjJa202mRoq9ErXx9_:-MYnvY-QBYQLnactOfFP:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

put this params into code markdown (\`xxx\`)
</blockquote></details>

Done.
___
*[README.md, line 21 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjJz-G5H7DMdPV47OH:-MYnvjW889tZCVenLwOV:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`and running with ...` -> `and running bench once more with ...`
</blockquote></details>

Done.
___
*[README.md, line 21 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjK2aX4slcDxpogxAz:-MYnvqn8CMp0k1WDcr3r:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L21)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

another result -> different result**s**
</blockquote></details>

Done.
___
*[README.md, line 22 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjKMik0xTOav6srUqK:-MYnvuZx6nP2c65N4x5w:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`is writing` -> `writes`
</blockquote></details>

Done.
___
*[README.md, line 41 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjKaks0DD6UpUuSZ6r:-MYnw9CTCRZW2n5CL0Op:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L41)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`... is supported`
or
`currently version from master branch is required`
</blockquote></details>

Done.
___
*[README.md, line 118 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjL5dLBfAeKjiUaV3W:-MYnwV7t-q15ou0TJUjX:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L118)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'd write it a bit more verbose:
`... parameter on start or at finish. It is ... responsibility to clear it if desired.`
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 30 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYk3QhQ6DZoS7UALp5r:-MYnw_1C0X-Fmf88iIU7:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/d26c3a18a3a26ea3b184e60adac012667cfb7cb5/bench/db_bench.cc#L30)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

This include is no more needed
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 578 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjNHoN79TCJ5dHFMbD:-MYo6RUi2oYP0sUVXbNB:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/bench/db_bench.cc#L578)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

do we close `kv_` somewhere now?
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 1124 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYk43z-8V5g4ECgnVqa:-MYo6Rpo5d01TO75CRZz:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/d26c3a18a3a26ea3b184e60adac012667cfb7cb5/bench/db_bench.cc#L1124)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

close on exit is probably still needed. 
</blockquote></details>

Done.
___
*[tests/test.py, line 145 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjQbF9Ak96UqJG3XqH:-MYnz9hJ0TNCvWuBm7Be:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/tests/test.py#L145)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps assign this to some variable to see if it contains proper count of results (2 in this case?)
</blockquote></details>

Done.
___
*[tests/test.py, line 147 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjUSNh2Hn-x6LXnJVq:-MYo6TqL9t7h4nR3Qsor:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/tests/test.py#L147)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add also a test with read-only workload and see if `found == 0`

and perhaps we should have a warning in the bench's code saying that you read nothing...?
</blockquote></details>

Done.
___
*[tests/test.py, line 167 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjPlFT4gxGBFFNHwuS:-MYo1dQc5uhcgiaPhBUV:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/tests/test.py#L167)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I'll be boring as hell, but perhaps pls add some comments (general one for the test itself and here in the code, to describe what's going on)
</blockquote></details>

Done.
___
*[tests/test.py, line 173 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYk8Je-E3_obG017T0v:-MYo1de7DZrLfkxjSdrP:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/tests/test.py#L173)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It would be good, if you add comment with example of data, which  you are parsing. 
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 4 files at r2, 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-:-MYos0Da6I4-tA3joHJI:bnfp4nl)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[README.md, line 118 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/73#-MYjL5dLBfAeKjiUaV3W:-MYopVUj8c_f2zchnarX:bb74ptu) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a21e60c7a9bb64a1d73315ec6a57d90035140e21/README.md#L118)):*
<details><summary><i>Previously, JanDorniak99 (Jan Dorniak) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

Thx!

**Pull request merged**
