### PR TITLE
Clang format

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/43)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/43)* status: 0 of 11 files reviewed, 1 unresolved discussion

___
*[Makefile, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkn07t4uNI_xyFHbHh:-MOkn07v8xlrMVBBT0er:b3bp46h) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/Makefile#L22)):*
> ```Makefile
> 
> cpp-format:
> 	find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\)' -exec clang-format -style=file -i {} \;
> ```

@lukaszstolarczuk
Do you have an idea how to better implement this target?

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 11 of 11 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/43)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[.clang-format, line 23 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOku9x23e7mAg25qdTd:-MOku9x23e7mAg25qdTe:bw5d09a) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/.clang-format#L23)):*
> ```YAML
> BreakBeforeBraces: Custom
> BreakStringLiterals: false
> ColumnLimit: 90
> ```

make this limit bigger perhaps? we didn't want to change this in pmemkv, not to mess with package maintainers/developer/etc (and not vandalize git history)
___
*[.git-blame-ignore-revs, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOku1Jm7EMkSbFvUp2N:-MOku1Jm7EMkSbFvUp2O:b-xjtlam) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/.git-blame-ignore-revs#L2)):*
> ```
> # Format c++ code with clang-format
> c3562931ad3fa06874471e066a95efca5b1bd5d8
> ```

that shall be updated after merge, I guess
___
*[Makefile, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkn07t4uNI_xyFHbHh:-MOkt0ED8jBnoh9lyoYJ:b-gxuu43) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/Makefile#L22)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

@lukaszstolarczuk
Do you have an idea how to better implement this target?
</blockquote></details>

hmm not really. Maybe without regex something like:
`find . -iname *.h* -o -iname *.c* -exec clang-format -style=file -i {} \;`
(it worked for me)
___
*[bench/port/port_posix.cc, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkv7NB2hgdsLR8B8Sz:-MOkv7NB2hgdsLR8B8T-:bqs0xzg) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/bench/port/port_posix.cc#L4)):*
> ```cpp
> // Use of this source code is governed by a BSD-style license that can be
> // found in the LICENSE-BSD file. See the AUTHORS file for names of contributors.
> ```

now you have to add Intel license...?

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/43)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex)

___
*[Makefile, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkvyuW27Z8tm4oZcUB:-MOkvyuX82ZpdnbAYhcb:b-m6nngu) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/Makefile#L22)):*
> ```Makefile
> 
> cpp-format:
> 	find . -regex '.*\.\(cpp\|hpp\|cc\|cxx\)' -exec clang-format -style=file -i {} \;
> ```

och, perhaps make the command already `clang-format-9`, without it it may not work in some new distros;

and pls add short note in README

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/43)* status: all files reviewed, 5 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[.clang-format, line 23 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOku9x23e7mAg25qdTd:-MOl7YAGEQIG5bE8NcZ6:b8wluwl) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/.clang-format#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

make this limit bigger perhaps? we didn't want to change this in pmemkv, not to mess with package maintainers/developer/etc (and not vandalize git history)
</blockquote></details>

100?  
110 is maximum which I may display in two columns on screen with 1920x1200 resolution with DejaVu Sans Mono Regular size 10 
___
*[.git-blame-ignore-revs, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOku1Jm7EMkSbFvUp2N:-MOl6SwV2kq8a0AgaXBa:buqzvyx) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/.git-blame-ignore-revs#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that shall be updated after merge, I guess
</blockquote></details>

no, merge creates marge commit and do not change underlying commits sha.
It should be changed after rebase. 
___
*[Makefile, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkvyuW27Z8tm4oZcUB:-MOl6mvGBKYnOvjIKKCp:b-z5qcrg) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/Makefile#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

och, perhaps make the command already `clang-format-9`, without it it may not work in some new distros;

and pls add short note in README
</blockquote></details>

as I noted in commit message, it's "clang-format-10.0.1" 
___
*[Makefile, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkn07t4uNI_xyFHbHh:-MOlBR8e4rG-ByIawV-v:ba77ql3) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/Makefile#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm not really. Maybe without regex something like:
`find . -iname *.h* -o -iname *.c* -exec clang-format -style=file -i {} \;`
(it worked for me)
</blockquote></details>

almost work ;) reformatted also .clang-format.  
This approach doesn't work for me very well.  I changed to 
```
find . -iname *.h -o -iname *.cc -exec clang-format -i {} \;
```
and does not reformat .h files. 
I prefer to left it with regex. 
___
*[bench/port/port_posix.cc, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkv7NB2hgdsLR8B8Sz:-MOl6x_06oxWQ4XnAt4s:b-6p8o9a) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/bench/port/port_posix.cc#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

now you have to add Intel license...?
</blockquote></details>

I'm not sure, as I do not change any logic structure in this commit. But probably yes :/

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/43)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[.clang-format, line 23 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOku9x23e7mAg25qdTd:-MOlU3LJC0kGUsQ9BaOW:bmc4gqh) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/.clang-format#L23)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

100?  
110 is maximum which I may display in two columns on screen with 1920x1200 resolution with DejaVu Sans Mono Regular size 10 
</blockquote></details>

100 seems reasonable
___
*[.git-blame-ignore-revs, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOku1Jm7EMkSbFvUp2N:-MOlU9vT1KU4o9zUTjNV:b-sme0rj) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/.git-blame-ignore-revs#L2)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

no, merge creates marge commit and do not change underlying commits sha.
It should be changed after rebase. 
</blockquote></details>

hmm.. right, mea culpa
___
*[Makefile, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkvyuW27Z8tm4oZcUB:-MOlUXcI0yZbnbLTTICH:b-gsohu2) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/Makefile#L22)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

as I noted in commit message, it's "clang-format-10.0.1" 
</blockquote></details>

och, sry, I've missed the commit message, but then, make the exec command `clang-format-10`
___
*[Makefile, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkn07t4uNI_xyFHbHh:-MOlUix2E3yCVcIwkUfW:b-opr5h5) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/Makefile#L22)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

almost work ;) reformatted also .clang-format.  
This approach doesn't work for me very well.  I changed to 
```
find . -iname *.h -o -iname *.cc -exec clang-format -i {} \;
```
and does not reformat .h files. 
I prefer to left it with regex. 
</blockquote></details>

both works for me
___
*[bench/port/port_posix.cc, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkv7NB2hgdsLR8B8Sz:-MOlUs501vo6BgaD-BI1:bqtb00) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/bench/port/port_posix.cc#L4)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I'm not sure, as I do not change any logic structure in this commit. But probably yes :/
</blockquote></details>

that's why I'm asking.. :D

**Comment by karczex** [comment]
___
*[.git-blame-ignore-revs, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOku1Jm7EMkSbFvUp2N:-MOmKAD24OmKej93hq4S:b-v4zd0p) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/.git-blame-ignore-revs#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. right, mea culpa
</blockquote></details>

Should be checked before merge.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/43)* status: 1 of 25 files reviewed, 4 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[.clang-format, line 23 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOku9x23e7mAg25qdTd:-MOq1fMJ0g6Kl_ylxXy-:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/.clang-format#L23)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

100 seems reasonable
</blockquote></details>

Done.
___
*[Makefile, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkvyuW27Z8tm4oZcUB:-MOpFSyeEVotSJ7iFTDz:bjnpbsd) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/Makefile#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

och, sry, I've missed the commit message, but then, make the exec command `clang-format-10`
</blockquote></details>

It's hard to make it portable. 
On ubuntu you have clang-format-10 and clang-format-9 binaries. However on fedora you have only clang-format, so I would rather leave it as is. 
___
*[Makefile, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkn07t4uNI_xyFHbHh:-MOq1iyLC9kJdxbXyyrK:b-af5g2n) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/Makefile#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

both works for me
</blockquote></details>

I used makefile magic instead of find magic.

**Comment by karczex** [comment]
___
*[bench/util/histogram.cc, line 12 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOq33IZ6fwAAKqUMq2h:-MOq33IZ6fwAAKqUMq2i:b3kqx) ([raw file](https://github.com/pmem/pmemkv-bench/blob/f745974942f731495c036561c43be00eab9de384/bench/util/histogram.cc#L12)):*
> ```cpp
> namespace leveldb
> {
> ```

.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/43)* status: 0 of 25 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[bench/port/port_posix.cc, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkv7NB2hgdsLR8B8Sz:-MOqDFY70atJw1HZuxCd:bmfxq1z) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/bench/port/port_posix.cc#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

that's why I'm asking.. :D
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 7 of 24 files at r2, 18 of 18 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/43)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[.git-blame-ignore-revs, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOku1Jm7EMkSbFvUp2N:-MOqTOAw3mu-jIW0r0mu:bstmfcd) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/.git-blame-ignore-revs#L2)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Should be checked before merge. 
</blockquote></details>

it's already wrong, FYI ;)
___
*[Makefile, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkvyuW27Z8tm4oZcUB:-MOqTrVG8-kGAUAI7DW1:b8g91tu) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/Makefile#L22)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It's hard to make it portable. 
On ubuntu you have clang-format-10 and clang-format-9 binaries. However on fedora you have only clang-format, so I would rather leave it as is. 
</blockquote></details>

`clang-format` is a moving target; on some newer distro this may reformat the whole code again (it's not a problem for us, but in case of potential ext. devs; we can set fixed version in CI)
___
*[Makefile, line 24 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOqVBxNB4-LFIpYiYGf:-MOqVBxNB4-LFIpYiYGg:bihwmtz) ([raw file](https://github.com/pmem/pmemkv-bench/blob/76de3c1804a1f72566453737e99f254e2a270b34/Makefile#L24)):*
> ```Makefile
> 	PMEM_IS_PMEM_FORCE=1 ./pmemkv_bench --db=/dev/shm/pmemkv --db_size_in_gb=1 --histogram=1
> 
> cppformat: $(CPP_FILES)
> ```

why do we need another target `$(CPPFILES)` ? can't it be done in a single `cppformat` target?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/43)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[Makefile, line 24 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOqVBxNB4-LFIpYiYGf:-MPckmyG7VOMEb1runkG:bud3q92) ([raw file](https://github.com/pmem/pmemkv-bench/blob/76de3c1804a1f72566453737e99f254e2a270b34/Makefile#L24)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why do we need another target `$(CPPFILES)` ? can't it be done in a single `cppformat` target?
</blockquote></details>

No. 
Target $(CPPFILES) is in fact list of dynamically generated parallel targets - one for each source file. 
On the other hand cppformat is aggregator, which provides simple interface for the user. 

Pretty good reading about Phony targets: 
https://www.gnu.org/software/make/manual/html_node/Phony-Targets.html

**Comment by karczex** [comment]
___
*[Makefile, line 22 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOkvyuW27Z8tm4oZcUB:-MPdmQ-F38bvdo-R0clD:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/Makefile#L22)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`clang-format` is a moving target; on some newer distro this may reformat the whole code again (it's not a problem for us, but in case of potential ext. devs; we can set fixed version in CI)
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/43)* status: 23 of 25 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[.git-blame-ignore-revs, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/43#-MOku1Jm7EMkSbFvUp2N:-MPdmeRe-ny-O_NLguy9:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/759b93fef40c98a8aa061ba926f726616ab59d9c/.git-blame-ignore-revs#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's already wrong, FYI ;)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/43)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
