### PR TITLE
Introduce 'disjoint' flag

### PR DESCRIPTION
**Pull request by igchor**
It can be used to run operations on disjoint sets of keys in each thread.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/38)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/38)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @igchor)

___
*[bench/db_bench.cc, line 9 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/38#-MNYoDieDK4NEPmppgJt:-MNYoDieDK4NEPmppgJu:b-8mxykc) ([raw file](https://github.com/pmem/pmemkv-tools/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L9)):*
> ```cpp
> // (found in the LICENSE file in the root directory).
> 
> // Copyright (c) 2017-2019, Intel Corporation
> ```

-2020
___
*[bench/db_bench.cc, line 37 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/38#-MNYyeaT8A6hkMT8mLEZ:-MNYyeaT8A6hkMT8mLE_:b-ftzw5z) ([raw file](https://github.com/pmem/pmemkv-tools/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L37)):*
> ```cpp
>         "                           (note: when pool path is non-existing, value should be > 0)\n"
>         "--histogram=<0|1>          (show histograms when reporting latencies)\n"
>         "--num=<integer>            (number of keys to place in database, default: 1000000)\n"
> ```

I believe it could be mentioned that it's per thread (unless disjoint is used... which is a little confusing, tbh)
___
*[bench/db_bench.cc, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/38#-MNYuTNV0-U4gngjq_tJ:-MNYuTNV0-U4gngjq_tK:b1633w9) ([raw file](https://github.com/pmem/pmemkv-tools/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L47)):*
> ```cpp
>         "In other words, 9 gets for every 1 put.) type: int32 default: 90\n"
>         "--disjoint=<0|1>           (specifies whether each thread works on disjoint set of keys. "
>         "0 means that each thread reads/writes to the db using all keys between 0 and `num`, so that "
> ```

I believe it's not clear right now (or I'm understanding it poorly), shouldn't it be something like:
`0 means that all threads read from/write to the db  using any key between 0 and 'num', ...` ?
___
*[bench/db_bench.cc, line 49 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/38#-MNYuyUfDUPwoGJ9r5a3:-MNYuyUfDUPwoGJ9r5a4:b-sqbkp1) ([raw file](https://github.com/pmem/pmemkv-tools/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L49)):*
> ```cpp
>         "0 means that each thread reads/writes to the db using all keys between 0 and `num`, so that "
>         "number of ops is `threads` * `num`. 1 means that each thread performs reads/writes using "
>         "only [`thread_id` * `num` / `threads`, (`thread_id` + 1) * `num` / `threads`] subset of keys, "
> ```

I believe, right hand parenthesis in this subset should be `)`
___
*[bench/db_bench.cc, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/38#-MNYxxeHAgtOokLJ0YEW:-MNYxxeHAgtOokLJ0YEX:b-rq98g9) ([raw file](https://github.com/pmem/pmemkv-tools/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L50)):*
> ```cpp
>         "number of ops is `threads` * `num`. 1 means that each thread performs reads/writes using "
>         "only [`thread_id` * `num` / `threads`, (`thread_id` + 1) * `num` / `threads`] subset of keys, "
>         "so that total number of ops is `num` \n"
> ```

1. please close the description with `)`
2. default value?
___
*[bench/db_bench.cc, line 674 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/38#-MNYvjx4DkTVO8FHYrho:-MNYvjx4DkTVO8FHYrhp:b1hm62q) ([raw file](https://github.com/pmem/pmemkv-tools/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L674)):*
> ```cpp
>         Slice key = AllocateKey(key_guard);
> 
>         auto num = FLAGS_disjoint ? num_ / FLAGS_threads : reads_;
> ```

`reads_` ?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/38)* status: 0 of 1 files reviewed, 6 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 9 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/38#-MNYoDieDK4NEPmppgJt:-MOk7FBv0Kw7GgQiHIuF:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

-2020
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 37 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/38#-MNYyeaT8A6hkMT8mLEZ:-MOk7KcaAvNyxv4lSqp9:brjipga) ([raw file](https://github.com/pmem/pmemkv-bench/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L37)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe it could be mentioned that it's per thread (unless disjoint is used... which is a little confusing, tbh)
</blockquote></details>

Well, this is the (max) number of element in database after inserts. Disjoint, in case of inserts, just tells how those inserts should be done - either all threads put all keys or each thread only puts it's own independent subset - the end result will be the same (on avarage).
___
*[bench/db_bench.cc, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/38#-MNYuTNV0-U4gngjq_tJ:-MOk9EvM2pz62fS2vm9G:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe it's not clear right now (or I'm understanding it poorly), shouldn't it be something like:
`0 means that all threads read from/write to the db  using any key between 0 and 'num', ...` ?
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 49 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/38#-MNYuyUfDUPwoGJ9r5a3:-MOk9NGW3tcPWo2u3Qr7:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L49)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe, right hand parenthesis in this subset should be `)`
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 50 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/38#-MNYxxeHAgtOokLJ0YEW:-MOk9Kq67wSuEUdsux5t:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L50)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. please close the description with `)`
2. default value?
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 674 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/38#-MNYvjx4DkTVO8FHYrho:-MOk9bNLByCiNTZOfXQw:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L674)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`reads_` ?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/38#-:-MOkWiHHBmRNKwxzpe8f:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

___
*[bench/db_bench.cc, line 37 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/38#-MNYyeaT8A6hkMT8mLEZ:-MOkUGb98DsB00xtZ_6T:b-ntddv6) ([raw file](https://github.com/pmem/pmemkv-bench/blob/2e78f5eb48f4aa2e2de6218f50339aac23ae2878/bench/db_bench.cc#L37)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Well, this is the (max) number of element in database after inserts. Disjoint, in case of inserts, just tells how those inserts should be done - either all threads put all keys or each thread only puts it's own independent subset - the end result will be the same (on avarage).
</blockquote></details>

I guess I've read the code wrong - each thread (e.g. in DoWrite) run from 0 (start) to num_ (end) - but it looks they are overwritten, so you're right, 'num' is the max element count.

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/38#-:-MOpskdG2kJwnM_s2RhU:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
