### PR TITLE
Add templates for github issues

### PR DESCRIPTION
**Pull request by karczex**
preview: https://github.com/karczex/pmemkv-tools/issues

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/51)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/51#-:-MRTpON-0bQQ-M5JIayb:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/51)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[.github/ISSUE_TEMPLATE/feature.md, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/51#-MRTrPOZ9RoQh1Fn47Bc:-MRTrPOZ9RoQh1Fn47Bd:b-agz5ff) ([raw file](https://github.com/pmem/pmemkv-bench/blob/719fb762d74066be8fd1450b4103ce106f190f05/.github/ISSUE_TEMPLATE/feature.md#L3)):*
> ```Markdown
> ---
> name: Feature
> about: Feature your request
> ```

I know we have it like that in pmemkv, but... what does it mean? :D shouldn't it be `Request a feature`?
___
*[.github/ISSUE_TEMPLATE/question.md, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/51#-MRTqchx5ogZ4pZmrGKw:-MRTqchx5ogZ4pZmrGKx:b-272pgr) ([raw file](https://github.com/pmem/pmemkv-bench/blob/719fb762d74066be8fd1450b4103ce106f190f05/.github/ISSUE_TEMPLATE/question.md#L3)):*
> ```Markdown
> ---
> name: Question
> about: Do you have question regarding pmemkv? Don't hesitate to ask.
> ```

`regarding pmemkv-bench`

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/51)* status: 1 of 3 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[.github/ISSUE_TEMPLATE/feature.md, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/51#-MRTrPOZ9RoQh1Fn47Bc:-MRTwrYU-tPLFBYj-aAl:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/719fb762d74066be8fd1450b4103ce106f190f05/.github/ISSUE_TEMPLATE/feature.md#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I know we have it like that in pmemkv, but... what does it mean? :D shouldn't it be `Request a feature`?
</blockquote></details>

Done.
___
*[.github/ISSUE_TEMPLATE/question.md, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/51#-MRTqchx5ogZ4pZmrGKw:-MRTwuLT1jA5sbmulvRJ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/719fb762d74066be8fd1450b4103ce106f190f05/.github/ISSUE_TEMPLATE/question.md#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`regarding pmemkv-bench`
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/51#-:-MRU20wkCURijbNJrRi4:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
