### PR TITLE
Clean and extend readme

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
and add CONTRIBUTING.md

Preview: https://github.com/lukaszstolarczuk/pmemkv-bench/tree/clean-readme

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/66)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/66)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[CONTRIBUTING.md, line 26 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/66#-MVL3BqK9VHKAOrNZsos:-MVL3BqLD65-nOxafa1V:bvlbmjl) ([raw file](https://github.com/pmem/pmemkv-bench/blob/df15e156dca0b8bba41b592e28d6f1540fe49279/CONTRIBUTING.md#L26)):*
> ```
> version exactly **9.0** is required.
> ```
11
, 10 would be also OK, but we have hardcoded version in Makefile
___
*[CONTRIBUTING.md, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/66#-MVL3lMx7TL6FLdvbZp_:-MVL3lMx7TL6FLdvbZpa:b6pkaje) ([raw file](https://github.com/pmem/pmemkv-bench/blob/df15e156dca0b8bba41b592e28d6f1540fe49279/CONTRIBUTING.md#L34)):*
> ```Markdown
> **NOTE: If you do decide to implement code changes and contribute them,
> please make sure you agree your contribution can be made available under the
> [BSD-style License used for pmemkv-bench](LICENSE).**
> ```

Apache-2.0

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/66)* status: 0 of 2 files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[CONTRIBUTING.md, line 26 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/66#-MVL3BqK9VHKAOrNZsos:-MVLBDML1Rm0XjAPYKA0:b-2t9kly) ([raw file](https://github.com/pmem/pmemkv-bench/blob/df15e156dca0b8bba41b592e28d6f1540fe49279/CONTRIBUTING.md#L26)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

> ```
> version exactly **9.0** is required.
> ```
11
, 10 would be also OK, but we have hardcoded version in Makefile
</blockquote></details>

10 may be acceptable for now, but that may change in the future, I guess... so I left it with just 11
___
*[CONTRIBUTING.md, line 34 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/66#-MVL3lMx7TL6FLdvbZp_:-MVLF9jG3QsybL9nBvIu:b4855pb) ([raw file](https://github.com/pmem/pmemkv-bench/blob/df15e156dca0b8bba41b592e28d6f1540fe49279/CONTRIBUTING.md#L34)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Apache-2.0
</blockquote></details>

Thanks! Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 2 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/66)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/66#-:-MV_NG99-Aa3ILwbECdA:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
