### PR TITLE
Remove dead code

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/40)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 12 of 12 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/40#-:-MO6XX1g8d5O_5VBb6LD:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[README.md, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/40#-MO6U8Ci0LhwPdG1xo95:-MO6U8Cj1dz2ytEHJStS:b-sgukgr) ([raw file](https://github.com/pmem/pmemkv-bench/blob/22ade9f55dc2301cb8d6f509aa6c054ddf9e267d/README.md#L2)):*
> ```Markdown
> # pmemkv-tools
> Optional tools and utilities for pmemkv
> ```

update pls

**Comment by lukaszstolarczuk** [comment]
perhaps, if any of this iteration/baseline scripts may be useful we should file an issue in this repo to port it (someday) to proper repo(s).

**Comment by karczex** [comment]
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/40#-MO6U8Ci0LhwPdG1xo95:-MO6bG0R1O5gFzk9JchI:bmtyapb) ([raw file](https://github.com/pmem/pmemkv-bench/blob/22ade9f55dc2301cb8d6f509aa6c054ddf9e267d/README.md#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

update pls
</blockquote></details>

I was thinking of it, but probably this should be updated as part of name change.

**Comment by karczex** [comment]
Any really useful part is storage_efficiency, which was implemented only for ruby - so we may port it there. 
I opened an issue: https://github.com/pmem/pmemkv-ruby/issues/45

I mentioned in https://github.com/pmem/pmemkv-java/issues/99, we need such test also in java.  
Issue in this repository is already opened https://github.com/pmem/pmemkv-bench/issues/39

**Comment by karczex** [comment]
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/40#-MO6U8Ci0LhwPdG1xo95:-MO6ftKH5lSWEn1RaGVO:bn42vw9) ([raw file](https://github.com/pmem/pmemkv-bench/blob/22ade9f55dc2301cb8d6f509aa6c054ddf9e267d/README.md#L2)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I was thinking of it, but probably this should be updated as part of name change.
</blockquote></details>

I didn't noticed, the name changed in meantime. 
Done.

**Comment by karczex** [comment]
___
*[README.md, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/40#-MO6U8Ci0LhwPdG1xo95:-MO6g-a184EY3VrOprdN:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/22ade9f55dc2301cb8d6f509aa6c054ddf9e267d/README.md#L2)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

I didn't noticed, the name changed in meantime. 
Done. 
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/40)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/40#-MO6uw-z2n6vOXlXOH8f:-MO6uw-z2n6vOXlXOH8g:b-vts3xe) (no related file):*
hmm.. perhaps update also gitignore file

---

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/40)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[README.md, line 76 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/40#-MOAq6ks1KNaa8QrgStc:-MOAq6ks1KNaa8QrgStd:b-4qxvou) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dee9d723a8657b41859b896105c4bdf36694db33/README.md#L76)):*
> ```Markdown
> 
> ```
> export LD_LIBRARY_PATH=</path/to/libpmemkv.so.1>
> ```

that might be a bit misleading - it's not path to the libpmemkv.so but a path to directory in which libpmemkv.so is located

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/40)* status: 11 of 13 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/40#-MO6uw-z2n6vOXlXOH8f:-MOBT5AyAeDKHvvf7qTC:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm.. perhaps update also gitignore file
</blockquote></details>

Done.

---
___
*[README.md, line 76 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/40#-MOAq6ks1KNaa8QrgStc:-MOBT3k31pbik1SWLKdX:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dee9d723a8657b41859b896105c4bdf36694db33/README.md#L76)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

that might be a bit misleading - it's not path to the libpmemkv.so but a path to directory in which libpmemkv.so is located
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/40)* status: all files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

___
*[README.md, line 74 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/40#-MOBYxcd5QnOAPmz0h-3:-MOBYxcd5QnOAPmz0h-4:bqt3yg4) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0b7ac2b763ffa8e3c19518aeaff2a82f53df2086/README.md#L74)):*
> ```Markdown
> 
> If pmemkv is installed in some non-standard path, `LD_LIBRARY_PATH` variable should be set
> to the directory which contain `libpmemkv.so.1` file
> ```

contains

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/40)* status: 12 of 13 files reviewed, 2 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

___
*[README.md, line 74 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/40#-MOBYxcd5QnOAPmz0h-3:-MOC62xe4wFoOKfUsIfD:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0b7ac2b763ffa8e3c19518aeaff2a82f53df2086/README.md#L74)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

contains
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/40)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/40)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
