### PR TITLE
Remove fix

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/47)

### CODE REVIEW

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/47)* status: all files reviewed, 5 unresolved discussions (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQm6tLC4z8VS3tO_B0k:-MQm6tLC4z8VS3tO_B0l:b-npwoom) (no related file):*
in second commit message, I'd just write it fixes the behavior of fresh_db, cleaning "the pool file" not destroying it - that issue was one specific use case, perhaps there's more ;)  (actually you can extend the commit message, not replace it with my words ;) )

also, `from` not `form`

---
___
*[Dockerfile.ubuntu-20.04, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQm5jUN3hiIwwthgST-:-MQm5jUN3hiIwwthgST0:bb6ht36) ([raw file](https://github.com/pmem/pmemkv-bench/blob/157fc0ac216f3910d87b6d66257eb60ab71a0bde/Dockerfile.ubuntu-20.04#L2)):*
> ```
> # SPDX-License-Identifier: Apache-2.0
> # Copyright 2016-2020, Intel Corporation
> ```

2021
___
*[Makefile, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQm5ohb-NHN4no5a3Yg:-MQm5ohb-NHN4no5a3Yh:b3kqx) ([raw file](https://github.com/pmem/pmemkv-bench/blob/157fc0ac216f3910d87b6d66257eb60ab71a0bde/Makefile#L2)):*
> ```Makefile
> # SPDX-License-Identifier: Apache-2.0
> # Copyright 2017-2020, Intel Corporation
> ```

.
___
*[bench/db_bench.cc, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQm5pmhEtGfQQvnsqav:-MQm5pmhEtGfQQvnsqaw:b3kqx) ([raw file](https://github.com/pmem/pmemkv-bench/blob/157fc0ac216f3910d87b6d66257eb60ab71a0bde/bench/db_bench.cc#L10)):*
> ```cpp
> 
> // SPDX-License-Identifier: Apache-2.0
> // Copyright 2017-2020, Intel Corporation
> ```

.
___
*[bench/db_bench.cc, line 701 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQm6hquD8MFTW2-ENnW:-MQm6hquD8MFTW2-ENnX:b51ct5d) ([raw file](https://github.com/pmem/pmemkv-bench/blob/157fc0ac216f3910d87b6d66257eb60ab71a0bde/bench/db_bench.cc#L701)):*
> ```cpp
> 			}
> 			auto start = g_env->NowMicros();
> 			/* Remove pmempool file. This should be
> ```

just `pool file`

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/47)* status: all files reviewed, 6 unresolved discussions (waiting on @karczex)

___
*[bench/db_bench.cc, line 704 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQpqs1G10wGWOk8Ctb3:-MQpqs1H9tWW7SDnHY-M:b-ujafxp) ([raw file](https://github.com/pmem/pmemkv-bench/blob/157fc0ac216f3910d87b6d66257eb60ab71a0bde/bench/db_bench.cc#L704)):*
> ```cpp
> 			 * implemented using libpmempool for backward
> 			 * compatibility. */
> 			if (pmempool_rm(FLAGS_db, 0) != 0) {
> ```

What if the pool does not exist?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/47)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[Dockerfile.ubuntu-20.04, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQm5jUN3hiIwwthgST-:-MQrJkBXDxW3N3q1iVBf:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/157fc0ac216f3910d87b6d66257eb60ab71a0bde/Dockerfile.ubuntu-20.04#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[Makefile, line 2 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQm5ohb-NHN4no5a3Yg:-MQrJkvc4N2O6mr4RdnB:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/157fc0ac216f3910d87b6d66257eb60ab71a0bde/Makefile#L2)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQm5pmhEtGfQQvnsqav:-MQrJluB5KNl6wsAHrCj:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/157fc0ac216f3910d87b6d66257eb60ab71a0bde/bench/db_bench.cc#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 701 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQm6hquD8MFTW2-ENnW:-MQrJnMP5e87yBLL9l2L:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/157fc0ac216f3910d87b6d66257eb60ab71a0bde/bench/db_bench.cc#L701)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

just `pool file`
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 704 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQpqs1G10wGWOk8Ctb3:-MQrKARGDIRbhtfT7x2w:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/157fc0ac216f3910d87b6d66257eb60ab71a0bde/bench/db_bench.cc#L704)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

What if the pool does not exist?
</blockquote></details>

Done.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/47)* status: 0 of 3 files reviewed, 6 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQm6tLC4z8VS3tO_B0k:-MQrKX9F5_jCXJZ7Ns4a:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

in second commit message, I'd just write it fixes the behavior of fresh_db, cleaning "the pool file" not destroying it - that issue was one specific use case, perhaps there's more ;)  (actually you can extend the commit message, not replace it with my words ;) )

also, `from` not `form`
</blockquote></details>

Done.

---

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/47)* status: 0 of 3 files reviewed, 7 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 39 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQunWda8mdrKX2rJJbj:-MQunWda8mdrKX2rJJbk:b-13m15s) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1210bfea1c3d9e7351e31b84c400c45e15999bf5/bench/db_bench.cc#L39)):*
> ```cpp
> 	"                           (note: file on DAX filesystem, DAX device, or poolset file)\n"
> 	"--db_size_in_gb=<integer>  (size of persistent pool to create in GB, default: 0)\n"
> 	"                           (note: for existing poolset or device DAX configs use 0 or left default)\n"
> ```

I think it should rather be "... or leave the default value"

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/47)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[bench/db_bench.cc, line 701 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQuySgL9mp3E7mng2lp:-MQuySgL9mp3E7mng2lq:b-qfpvdm) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1210bfea1c3d9e7351e31b84c400c45e15999bf5/bench/db_bench.cc#L701)):*
> ```cpp
> 			}
> 			auto start = g_env->NowMicros();
> 			/* Remove pool file. This should be
> ```

hmm maybe consider adding an info (in README? in usage? ...?) that the pool may be cleared/removed in some cases

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/47)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 701 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-MQuySgL9mp3E7mng2lp:-MQvbgcSAYXkPHNgD3ge:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1210bfea1c3d9e7351e31b84c400c45e15999bf5/bench/db_bench.cc#L701)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm maybe consider adding an info (in README? in usage? ...?) that the pool may be cleared/removed in some cases
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-:-MQvbx3jBbfcUG-cgnfZ:bnfp4nl)* status: 2 of 4 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/47#-:-MQvdUQVDnCD9iwbL9RG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
