### PR TITLE
Add GHA workflow

### PR DESCRIPTION
**Pull request by karczex**
Workflow is based on prebuilt docker image from pmemkv
Depends on: https://github.com/pmem/pmemkv/pull/930

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/58)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/58)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MTZWSbd3NdiKfjaPwTx:-MTZWSbd3NdiKfjaPwTy:b-j2uivl) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9e61423da71fc581ab34150abb34122911a87625/Dockerfile#L1)):*
> ```Dockerfile
> # SPDX-License-Identifier: Apache-2.0
> ```

can't you use /utils/docker/images path for this file?
___
*[Dockerfile, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MTZWXZr8BQiJWRIviib:-MTZWXZs0EoStp5wvxEA:bk7a5wj) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9e61423da71fc581ab34150abb34122911a87625/Dockerfile#L3)):*
> ```Dockerfile
> # SPDX-License-Identifier: Apache-2.0
> # Copyright 2016-2021, Intel Corporation
> ```

perhaps add a short description, why this docker recipe is different 
___
*[.github/workflows/main.yml, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MTZX1k42dj-IHtgaY5i:-MTZX1k42dj-IHtgaY5j:b-rav5wh) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9e61423da71fc581ab34150abb34122911a87625/.github/workflows/main.yml#L4)):*
> ```YAML
> 
> jobs:
>   hello_world_job:
> ```

why this name? ;)
___
*[.github/workflows/main.yml, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MTZXXvEEJ19CJz5wy8i:-MTZXXvEEJ19CJz5wy8j:bs6e2nz) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9e61423da71fc581ab34150abb34122911a87625/.github/workflows/main.yml#L10)):*
> ```YAML
>       - name: Checkout
>         uses: actions/checkout@v2
>       - name: building test
> ```

it's not building test, I guess

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/58)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MTZWSbd3NdiKfjaPwTx:-MTZnLMo2iVSmki4vNwP:b9n9jpq) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9e61423da71fc581ab34150abb34122911a87625/Dockerfile#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can't you use /utils/docker/images path for this file?
</blockquote></details>

probably I could, but it would make copy step little bit ugly.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/58)* status: 0 of 5 files reviewed, 4 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[Dockerfile, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MTZWXZr8BQiJWRIviib:-MTZtHZUBs-PeE6czgid:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9e61423da71fc581ab34150abb34122911a87625/Dockerfile#L3)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

perhaps add a short description, why this docker recipe is different 
</blockquote></details>

Done.
___
*[.github/workflows/main.yml, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MTZX1k42dj-IHtgaY5i:-MTZtQUY5E3qBYZFEU-g:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9e61423da71fc581ab34150abb34122911a87625/.github/workflows/main.yml#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why this name? ;)
</blockquote></details>

Done.
___
*[.github/workflows/main.yml, line 10 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MTZXXvEEJ19CJz5wy8i:-MTZtTG_9yIQtMeAbApj:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9e61423da71fc581ab34150abb34122911a87625/.github/workflows/main.yml#L10)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

it's not building test, I guess
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 2 of 5 files at r1, 3 of 3 files at r2, 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/58)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[Dockerfile, line 5 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MT__bfh9PiQ2puC5xsZ:-MT__bfh9PiQ2puC5xs_:bu7794q) ([raw file](https://github.com/pmem/pmemkv-bench/blob/391c5eb888e0989a0b27a57110a17e2ec2289100/Dockerfile#L5)):*
> ```Dockerfile
> 
> #
> # Dockerfile for lightweight Docker-based Continues Integration process of pmemkv-bench.
> ```

Continuous ;)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/58)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[Dockerfile, line 5 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MT__bfh9PiQ2puC5xsZ:-MT_arHJ4Ou0OsglCiB0:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/391c5eb888e0989a0b27a57110a17e2ec2289100/Dockerfile#L5)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Continuous ;)
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 1 of 5 files at r1, 1 of 1 files at r3, 3 of 4 files at r4, 1 of 1 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/58)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[tests/test.py, line 6 at r5](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MTft4XBE5zI_gFth3-i:-MTft4XCE4YzuYsfJ9Tt:bymtss0) ([raw file](https://github.com/pmem/pmemkv-bench/blob/bc6ab3aee94a25f25b07375bd1c79d39227da089/tests/test.py#L6)):*
> ```Python
> import tempfile
> 
> project_path = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
> ```

dirname from dirname?
___
*[tests/test.py, line 8 at r5](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MTftAPE688Ujo43KeA0:-MTftAPF6EsS4qefp8vU:b-yynyg) ([raw file](https://github.com/pmem/pmemkv-bench/blob/bc6ab3aee94a25f25b07375bd1c79d39227da089/tests/test.py#L8)):*
> ```Python
> project_path = os.path.dirname(os.path.dirname(os.path.realpath(__file__)))
> sys.path.append(project_path)
> import run_benchmark as rb
> ```

imports to the top

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/58)* status: all files reviewed, 3 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

___
*[tests/test.py, line 6 at r5](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MTft4XBE5zI_gFth3-i:-MTjiVotC3-3YxT2m782:b75k9qx) ([raw file](https://github.com/pmem/pmemkv-bench/blob/bc6ab3aee94a25f25b07375bd1c79d39227da089/tests/test.py#L6)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

dirname from dirname?
</blockquote></details>

That's the way to get parent directory for imports.
___
*[tests/test.py, line 8 at r5](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-MTftAPE688Ujo43KeA0:-MTjggkf8p-ovSAHBN81:b9tyhw) ([raw file](https://github.com/pmem/pmemkv-bench/blob/bc6ab3aee94a25f25b07375bd1c79d39227da089/tests/test.py#L8)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

imports to the top
</blockquote></details>

It is on the top, just after configuration of sys.path - which is needed to import application code.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/58#-:-MTjjMw58QOVsx5xNnnH:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

**Pull request merged**
