### PR TITLE
Fix units in README and help

### PR DESCRIPTION
**Pull request by karczex**
Using predefined constants from std::ratio is more readable
than hardcoding multiplication.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/80)

### CODE REVIEW

**Review by KFilipek — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/80#-:-MkC6u6f66_4Bj9C7K1W:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/80)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[bench/db_bench.cc, line 759 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/80#-MkCGkAsD7NkReozP70-:-MkCGkAsD7NkReozP700:b-4yrspg) ([raw file](https://github.com/pmem/pmemkv-bench/blob/854c3c232a385de3638e85d3b4beb453db1f926c/bench/db_bench.cc#L759)):*
> ```cpp
> 		assert(kv_ == nullptr);
> 		auto start = g_env->NowMicros();
> 		auto size = FLAGS_db_size_in_gb * std::giga::num;
> ```

hmm... actually don't we want it to be GiB (instead of GB)? so perhaps the code was right and the description (in readme) was wrong... :wink:

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/80)* status: 0 of 2 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 759 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/80#-MkCGkAsD7NkReozP70-:-MkCQesnA92elGhsw4wB:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/854c3c232a385de3638e85d3b4beb453db1f926c/bench/db_bench.cc#L759)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm... actually don't we want it to be GiB (instead of GB)? so perhaps the code was right and the description (in readme) was wrong... :wink: 
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/80)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 759 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/80#-MkCGkAsD7NkReozP70-:-MkCT1mN22KcsdSkGf6Y:biphh7w) ([raw file](https://github.com/pmem/pmemkv-bench/blob/854c3c232a385de3638e85d3b4beb453db1f926c/bench/db_bench.cc#L759)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

```cpp
#include <iostream>
#include <ratio>
#include <cassert>
#include <cmath>

int GiBtoGB(int value) {
    int exp = 0;
    assert(value % 1000 == 0);
    for (;value != 1; exp++, value = value / 1000);
    return static_cast<int>(pow(1024, exp));
}

int main() {
    int x = std::giga::num;
    std::cout << x << std::endl;
    std::cout << GiBtoGB(x) << std::endl;
}
```
output:
```
1000000000
1073741824
```
then:
`auto size = FLAGS_db_size_in_gb * GiBtoGB(std::giga::num);`
and you will still use nice `std::giga::num`

**Comment by karczex** [comment]
___
*[bench/db_bench.cc, line 759 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/80#-MkCGkAsD7NkReozP70-:-MkwRUey3oJiyWmtPNE_:b-hafm9a) ([raw file](https://github.com/pmem/pmemkv-bench/blob/854c3c232a385de3638e85d3b4beb453db1f926c/bench/db_bench.cc#L759)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

```cpp
#include <iostream>
#include <ratio>
#include <cassert>
#include <cmath>

int GiBtoGB(int value) {
    int exp = 0;
    assert(value % 1000 == 0);
    for (;value != 1; exp++, value = value / 1000);
    return static_cast<int>(pow(1024, exp));
}

int main() {
    int x = std::giga::num;
    std::cout << x << std::endl;
    std::cout << GiBtoGB(x) << std::endl;
}
```
output:
```
1000000000
1073741824
```
then:
`auto size = FLAGS_db_size_in_gb * GiBtoGB(std::giga::num);`
and you will still use nice `std::giga::num`
</blockquote></details>

clever :) but the clue of the change was to make less code/ more readable

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 2 files at r2, all commit messages.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/80#-:-Ml92rQy0OevMIwiGL9d:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by KFilipek — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/80)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
