### PR TITLE
fix benchmarking volatile engines

### LINKED ISSUE #56: ISSUE: cannot measure read performance for volatile engines
# ISSUE: cannot measure read performance for volatile engines

## Environment Information

- pmemkv-bench version(s):                                           
- pmemkv version(s):                                                 
- libpmemobj-cpp version(s):                                         
- PMDK (libpmem/libpmemobj) package version(s):                      
- OS(es) version(s):                                                 
- kernel version(s):                                                 
- compiler, libraries, packaging and other related tools version(s): 

and possibly:
- TBB version(s):                                                    
- memkind version(s):                                                
- ndctl version(s):                                                  

## Please provide a reproduction of the bug:

execute bench with benchmarks=fillrandom,readrandom

## How often bug is revealed:

always

## Actual behavior:

readrandom does not find any elements - pool is closed after each benchmark

## Expected behavior:

readrandom finds all inserted elements

## Additional information about Priority and Help Requested:

Are you willing to submit a pull request with a proposed change? (Yes, No)  

Requested priority: (Showstopper, High, Medium, Low)

### PR DESCRIPTION
**Pull request by JanDorniak99**
Resolves #56

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/64)

### CODE REVIEW

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/64)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @JanDorniak99)

___
*[tests/test.py, line 32 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/64#-MUrn5C206locvey6DUY:-MUrn5C206locvey6DUZ:b-ga97cl) ([raw file](https://github.com/pmem/pmemkv-bench/blob/b736eb9375ef2fe5eb332f0542c3dc756b4c3e6c/tests/test.py#L32)):*
> ```Python
> 
> 
> @pytest.mark.parametrize(
> ```

you may change parameters to something like this: 

```python
@pytest.mark.parametrize(
    "engine,test_path,benchmarks",
    [
        ("cmap",  os.getenv('TEST_PATH', '/dev/shm/pmemkv'), "fillrandom,readrandom"),
        ("csmap",  os.getenv('TEST_PATH', '/dev/shm/pmemkv'), "fillrandom,readrandom"),
        ("vcmap", os.path.dirname(os.getenv('TEST_PATH', '/dev/shm/pmemkv')), "fillrandom,readrandom"),
        ("vsmap", os.path.dirname(os.getenv('TEST_PATH', '/dev/shm/pmemkv')), "fillrandom,readrandom"),
    ],
)
def test_json(engine, test_path, benchmarks):
```

It would be little bit more readable, and you would avoid `if is_volatile` logic inside test.

And you get readable test names for free: 
```
test.py::test_help PASSED                                                                                                                                                                                                              [ 20%]
test.py::test_json[cmap-/dev/shm/pmemkv-fillrandom,readrandom] ^[PASSED                                                                                                                                                                  [ 40%]
test.py::test_json[csmap-/dev/shm/pmemkv-fillrandom,readrandom] PASSED                                                                                                                                                                 [ 60%]
test.py::test_json[vcmap-/dev/shm-fillrandom,readrandom] PASSED                                                                                                                                                                        [ 80%]
test.py::test_json[vsmap-/dev/shm-fillrandom,readrandom] PASSED 
```


<!-- Sent from Reviewable.io -->

**Review by JanDorniak99 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/64)* status: 0 of 3 files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[tests/test.py, line 32 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/64#-MUrn5C206locvey6DUY:-MUrr3cL536ok7qZCTmK:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/b736eb9375ef2fe5eb332f0542c3dc756b4c3e6c/tests/test.py#L32)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

you may change parameters to something like this: 

```python
@pytest.mark.parametrize(
    "engine,test_path,benchmarks",
    [
        ("cmap",  os.getenv('TEST_PATH', '/dev/shm/pmemkv'), "fillrandom,readrandom"),
        ("csmap",  os.getenv('TEST_PATH', '/dev/shm/pmemkv'), "fillrandom,readrandom"),
        ("vcmap", os.path.dirname(os.getenv('TEST_PATH', '/dev/shm/pmemkv')), "fillrandom,readrandom"),
        ("vsmap", os.path.dirname(os.getenv('TEST_PATH', '/dev/shm/pmemkv')), "fillrandom,readrandom"),
    ],
)
def test_json(engine, test_path, benchmarks):
```

It would be little bit more readable, and you would avoid `if is_volatile` logic inside test.

And you get readable test names for free: 
```
test.py::test_help PASSED                                                                                                                                                                                                              [ 20%]
test.py::test_json[cmap-/dev/shm/pmemkv-fillrandom,readrandom] ^[PASSED                                                                                                                                                                  [ 40%]
test.py::test_json[csmap-/dev/shm/pmemkv-fillrandom,readrandom] PASSED                                                                                                                                                                 [ 60%]
test.py::test_json[vcmap-/dev/shm-fillrandom,readrandom] PASSED                                                                                                                                                                        [ 80%]
test.py::test_json[vsmap-/dev/shm-fillrandom,readrandom] PASSED 
```
</blockquote></details>

Done.


<!-- Sent from Reviewable.io -->

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/64#-:-MUrx9LHAIdXsFB-AEB5:bnfp4nl)* status: 0 of 3 files reviewed, all discussions resolved

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/64#-:-MUs-p1Z4s9AZGzwEbwc:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 2 of 3 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/64#-:-MUs5pzsDx1Kj26xOEqX:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @JanDorniak99)

**Pull request merged**
