### PR TITLE
Always collect histogram data

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/67)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/67#-:-MW-mRNI1CwWsFSq9PbB:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/67#-:-MW-r0OE-FrYJfzLJrvr:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by igchor — CHANGES_REQUESTED** [review]
Will our scripts work after this change? There is now some data printed which is not in csv, right?

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/67#-:-MW3N0Jd8H_RBINhgGBA:b4vz4yd)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[bench/db_bench.cc, line 91 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/67#-MW3KSZ06lTObTz4akqt:-MW3KSZ06lTObTz4akqu:bxwxxyq) ([raw file](https://github.com/pmem/pmemkv-bench/blob/f4c8de1dd550669d18e7b6fb3334462344f49437/bench/db_bench.cc#L91)):*
> ```cpp
> 
> // Print histogram of operation timings
> static bool FLAGS_histogram = false;
> ```

I guess this can be removed then?

**Comment by lukaszstolarczuk** [comment]
how this should work with the new, proposed flag?
https://github.com/pmem/pmemkv-bench/pull/65/commits/54e6d551a50e8d9ba3ad48993784df5231d22d48

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/67#-:-MW40an_09BYHXqBPDn0:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

**Pull request merged**
