### PR TITLE
Fix makefile targets and code formatting

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
Our makefile targets failed properly only if the last file was improper, not if e.g. first file was badly formatted.

By the way of this change I selected one version of black formatter, since I had different version on my machine and it wasn't compatible.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/76)

### CODE REVIEW

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/76#-:-MZS-2T24lSDW2JxFYY-:bnfp4nl)* status: 0 of 6 files reviewed, all discussions resolved

**Review by KFilipek — COMMENTED** [review]
> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/76)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[CONTRIBUTING.md, line 20 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/76#-MZS1Big09QVMowzdEow:-MZS1BihBSzFrYgTQzHB:b-359bzq) ([raw file](https://github.com/pmem/pmemkv-bench/blob/c234a80972549f0c5d5c809139f073de66bce0db/CONTRIBUTING.md#L20)):*
> ```Markdown
> ```
> 
> for python scripts (using python's formatter - black in ver. 21.4b2), use:
> ```

We missed "black" dependency in README.md.
I thing that we can bold "black" name here, but it's up to you.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/76)* status: 4 of 7 files reviewed, 1 unresolved discussion (waiting on @KFilipek)

___
*[CONTRIBUTING.md, line 20 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/76#-MZS1Big09QVMowzdEow:-MZSHixs8Dab13JZvzcV:b-jnowio) ([raw file](https://github.com/pmem/pmemkv-bench/blob/c234a80972549f0c5d5c809139f073de66bce0db/CONTRIBUTING.md#L20)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

We missed "black" dependency in README.md.
I thing that we can bold "black" name here, but it's up to you.
</blockquote></details>

yeah I know, but we have the reference to Dockerfile for the instruction. We just don't believe anyone is here for developing python, rather the db_bench itself

anyway, done, now it's more precise I hope

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/76#-:-M_-vL3YCl8GbIjvRHJn:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by karczex — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/76#-:-M_ykA6a9BHWWrnLLZDE:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
