### PR TITLE
utils: add script to create charts based on data stored in MongoDB

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
MongoDB connector, specified exactly to our use, aggregates and downloads
data for performance charts. Using plotly library charts are then
saved into an image for further use.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/71)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/71)* status: 0 of 6 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/71#-MXrBqa00cihu1B_URNg:-MXrBqa00cihu1B_URNh:b-hm7k43) (no related file):*
@igchor, should I include information about new requirements/dependencies in the commit msg...?

---

**Review by igchor — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/71)* status: 0 of 6 files reviewed, 2 unresolved discussions (waiting on @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/71#-MXrBqa00cihu1B_URNg:-MYJPEyk0Qf1l-1aNvW5:b-sugkgb) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

@igchor, should I include information about new requirements/dependencies in the commit msg...?
</blockquote></details>

Yes, that would nice, along with the link to the dependency and a license.

---
___
*[utils/charts/generate_charts.py, line 220 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/71#-MYJPYBF0VuXyaOxPN2j:-MYJPYBF0VuXyaOxPN2k:b-jjc8wp) ([raw file](https://github.com/pmem/pmemkv-bench/blob/11fe765b56bc3ca7bb23a197812d4460128ac30e/utils/charts/generate_charts.py#L220)):*
> ```Python
> 
>         ## standard MT benchmarks ##
>         aggregation_params["engines"] = ["csmap", "cmap"]
> ```

Could we put definition of those charts in a separate file and add possibility to pass path to this file to the actual script? So we could have configuration files, separate from the logic.

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 3 of 6 files at r1, 1 of 2 files at r3, 1 of 2 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/71#-:-MYOtl6L-2npZSmW2EB5:bnfp4nl)* status: 3 of 6 files reviewed, 2 unresolved discussions (waiting on @KFilipek and @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/71)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/71#-MXrBqa00cihu1B_URNg:-MYedYEg6LifUqXEnYQA:b-896fix) (no related file):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Yes, that would nice, along with the link to the dependency and a license.
</blockquote></details>

Done.

---
___
*[utils/charts/generate_charts.py, line 220 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/71#-MYJPYBF0VuXyaOxPN2j:-MYedDqdAKOHWxDTGCNj:badyjjh) ([raw file](https://github.com/pmem/pmemkv-bench/blob/11fe765b56bc3ca7bb23a197812d4460128ac30e/utils/charts/generate_charts.py#L220)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Could we put definition of those charts in a separate file and add possibility to pass path to this file to the actual script? So we could have configuration files, separate from the logic.
</blockquote></details>

will be done later, in sep. PR

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/71#-:-MYk1wLE0zKKlGK1ME-e:bnfp4nl)* status: 3 of 6 files reviewed, 1 unresolved discussion (waiting on @igchor and @KFilipek)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/71#-:-MYt3x9925Hr2l9RR4Ao:bnfp4nl)* status: 3 of 6 files reviewed, all discussions resolved (waiting on @KFilipek)

**Comment by lukaszstolarczuk** [comment]
I had to fix pyformat yet and BTW I renamed the files to snake_case

**Pull request merged**
