### PR TITLE
Add supprt for running multiple test cases for one build

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/53)

### CODE REVIEW

**Comment by KFilipek** [comment]
supprt -> support :)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/53)* status: all files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[run_benchmark.py, line 4 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/53#-MR_MeVU0T9T2Z6p70h4:-MR_MeVU0T9T2Z6p70h5:b-8mxykb) ([raw file](https://github.com/pmem/pmemkv-bench/blob/f47ebb3a90ed2a47806a42492465c616f87bc9f0/run_benchmark.py#L4)):*
> ```Python
> #
> # SPDX-License-Identifier: Apache-2.0
> # Copyright 2020, Intel Corporation
> ```

-2021
___
*[run_benchmark.py, line 276 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/53#-MR_MS_L4UuiD2UPyntI:-MR_MS_L4UuiD2UPyntJ:b5yf7i6) ([raw file](https://github.com/pmem/pmemkv-bench/blob/f47ebb3a90ed2a47806a42492465c616f87bc9f0/run_benchmark.py#L276)):*
> ```Python
>             and db_name
>             and db_collection
>         ):
> ```

align this line with one more tab perhaps...?
___
*[bench_scenarios/basic_bench.json, line 15 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/53#-MR_RPwJ5bLxxXfCWTbq:-MR_RPwJ5bLxxXfCWTbr:b-zhsqio) ([raw file](https://github.com/pmem/pmemkv-bench/blob/f47ebb3a90ed2a47806a42492465c616f87bc9f0/bench_scenarios/basic_bench.json#L15)):*
> ```JSON
>         },
>         "params": [
>             "--db=/dev/shm/pmemkv",
> ```

/dev/shm without PMEM_IS_PMEM_FORCE...? is that on purpose?
___
*[bench_scenarios/basic_build.json, line 3 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/53#-MRZi7DB1sZDmaWoKDX1:-MRZi7DC-s15cOwa5j7L:b-i9xk5c) ([raw file](https://github.com/pmem/pmemkv-bench/blob/f47ebb3a90ed2a47806a42492465c616f87bc9f0/bench_scenarios/basic_build.json#L3)):*
> ```JSON
> {
>     "db_bench": {
>         "repo_url": "https://github.com/pmem/pmemkv-tools.git",
> ```

you can update this url ;)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/53)* status: 2 of 4 files reviewed, 4 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[run_benchmark.py, line 276 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/53#-MR_MS_L4UuiD2UPyntI:-MRt286C0_y3pYd3F-tf:b9u0vpz) ([raw file](https://github.com/pmem/pmemkv-bench/blob/f47ebb3a90ed2a47806a42492465c616f87bc9f0/run_benchmark.py#L276)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

align this line with one more tab perhaps...?
</blockquote></details>

nope. This code is automatically formatted with black, and I would like to leave it as is. 
___
*[bench_scenarios/basic_bench.json, line 15 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/53#-MR_RPwJ5bLxxXfCWTbq:-MRt2kAE2Edc69c0GZYi:bwnhtjg) ([raw file](https://github.com/pmem/pmemkv-bench/blob/f47ebb3a90ed2a47806a42492465c616f87bc9f0/bench_scenarios/basic_bench.json#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

/dev/shm without PMEM_IS_PMEM_FORCE...? is that on purpose?
</blockquote></details>

Yes. I want to use this file in gha (as soon as we add it), and empty env would be good for testing. 
Probably name of file should be changed to test_bench.json

**Review by lukaszstolarczuk — COMMENTED** [review]
FYI, something went wrong with rebase & push ;)

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/53#-:-MRtyWW0-_gqFJMHYqUa:brc4kbo)* status: 0 of 53 files reviewed, 3 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

**Pull request closed without merging**
