### PR TITLE
Benchmarking scenarios

### PR DESCRIPTION
**Pull request by karczex**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 9 of 9 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex)

___
*[run_benchmark.py, line 298 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MSgVwj29savZBrrS7IP:-MSgVwj29savZBrrS7IQ:bn9dhko) ([raw file](https://github.com/pmem/pmemkv-bench/blob/4999bbae3234948c581668b9c86a63170e64baa8/run_benchmark.py#L298)):*
> ```Python
>     except KeyError as e:
>         logger.warning(
>             f"Environmet variable {e} was not specified, so results cannot be uploaded to the database"
> ```

Environmet -> Environment
___
*[bench_scenarios/basic_bench.json, line 14 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MSgWFP-3YWknDHdhXvE:-MSgWFP-3YWknDHdhXvF:bis4clb) ([raw file](https://github.com/pmem/pmemkv-bench/blob/4999bbae3234948c581668b9c86a63170e64baa8/bench_scenarios/basic_bench.json#L14)):*
> ```JSON
>     },
>     {
>         "env": {},
> ```

no PMEM_IS_PMEM_FORCE=1 when we're using /dev/shm/pmemkv?
___
*[bench_scenarios/generate_basic_scope.py, line 17 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MSgWSeo7NbF-mm3BS7Y:-MSgWSeo7NbF-mm3BS7Z:b-tawrc1) ([raw file](https://github.com/pmem/pmemkv-bench/blob/4999bbae3234948c581668b9c86a63170e64baa8/bench_scenarios/generate_basic_scope.py#L17)):*
> ```Python
> ]
> size = [8, 128]
> number_od_elements = 100000000
> ```

od -> of?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: 8 of 9 files reviewed, 3 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[bench_scenarios/basic_bench.json, line 14 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MSgWFP-3YWknDHdhXvE:-MShfCRKBw6z7CB1aE1i:b-xv2e05) ([raw file](https://github.com/pmem/pmemkv-bench/blob/4999bbae3234948c581668b9c86a63170e64baa8/bench_scenarios/basic_bench.json#L14)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

no PMEM_IS_PMEM_FORCE=1 when we're using /dev/shm/pmemkv?
</blockquote></details>

Probably need to change file name to test_bench json.  This is  test for empty env.
More tests should be added, when we add GHA to this repository.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: 6 of 9 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[run_benchmark.py, line 298 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MSgVwj29savZBrrS7IP:-MShij4KDOM5IoLwhNkM:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/4999bbae3234948c581668b9c86a63170e64baa8/run_benchmark.py#L298)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

Environmet -> Environment
</blockquote></details>

Done.
___
*[bench_scenarios/generate_basic_scope.py, line 17 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MSgWSeo7NbF-mm3BS7Y:-MShikw921UKWTrh8UhE:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/4999bbae3234948c581668b9c86a63170e64baa8/bench_scenarios/generate_basic_scope.py#L17)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

od -> of?
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
> Reviewed 3 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[run_benchmark.py, line 4 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MSho7t35FrjmF91BFYY:-MSho7t45SAl_l3z2bgg:bb6ht36) ([raw file](https://github.com/pmem/pmemkv-bench/blob/e5756ff0432091d5ce9b23c929504e94f09e895c/run_benchmark.py#L4)):*
> ```Python
> #
> # SPDX-License-Identifier: Apache-2.0
> # Copyright 2020, Intel Corporation
> ```

2021
___
*[bench_scenarios/generate_basic_scope.py, line 1 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MShoBC30rsv5lbRSWdM:-MShoBC30rsv5lbRSWdN:b-jb0csd) ([raw file](https://github.com/pmem/pmemkv-bench/blob/e5756ff0432091d5ce9b23c929504e94f09e895c/bench_scenarios/generate_basic_scope.py#L1)):*
> ```Python
> import json
> ```

License?

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: 7 of 9 files reviewed, 2 unresolved discussions (waiting on @KFilipek)

___
*[run_benchmark.py, line 4 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MSho7t35FrjmF91BFYY:-MT-jBbtExADUaE9_Gea:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/e5756ff0432091d5ce9b23c929504e94f09e895c/run_benchmark.py#L4)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

2021
</blockquote></details>

Done.
___
*[bench_scenarios/generate_basic_scope.py, line 1 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MShoBC30rsv5lbRSWdM:-MT-j8OZ3KbBGlL3OmXj:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/e5756ff0432091d5ce9b23c929504e94f09e895c/bench_scenarios/generate_basic_scope.py#L1)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

License?
</blockquote></details>

Done.

**Review by KFilipek — COMMENTED** [review]
Switch to clang-format-11, as debian for some reason contain
  clang-format-9 and clang-format-11. **Fortunetely** this switch doesn't
  change formatting
Fortunetely -> Fortunately

> Reviewed 2 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-:-MT5dVr42-TGLyjRWcCy:b1g2j5t)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 3 files at r2, 1 of 2 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: all files reviewed, 2 unresolved discussions (waiting on @karczex)

___
*[bench_scenarios/generate_basic_scope.py, line 45 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MT5xN1-3h5YeAjOz_ER:-MT5xN1-3h5YeAjOz_ES:b-c8n5bi) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/bench_scenarios/generate_basic_scope.py#L45)):*
> ```Python
>     benchmarks.extend(single_threaded_engines())
>     benchmarks_configuration = []
>     db_path = "/mnt/pmem0/pmemkv-bench"
> ```

maybe a parameter?
___
*[bench_scenarios/generate_basic_scope.py, line 49 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MT5x16e9ywFuZeKxMH0:-MT5x16e9ywFuZeKxMH1:b-6s2hbv) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/bench_scenarios/generate_basic_scope.py#L49)):*
> ```Python
>         benchmark_settings = {
>             "env": {
>                 "NUMACTL_CPUBIND": f"file:{os.path.dirname(db_path)}",
> ```

This will work for obj based engines but what about memkind based ones? They expect path to directory so dirname will return something like "/mnt"

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 6 of 9 files at r1, 1 of 3 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: all files reviewed, 10 unresolved discussions (waiting on @karczex)

___
*[Dockerfile.debian-testing, line 4 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKC7pM2IdZ6vZfehVn:-MTKC7pM2IdZ6vZfehVo:bbdjetz) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/Dockerfile.debian-testing#L4)):*
> ```
> # Copyright 2016-2021, Intel Corporation
> 
> FROM debian:testing
> ```

why switch from Ubuntu to Debian?
___
*[Makefile, line 31 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKC01a3PSTKZO91rCQ:-MTKC01a3PSTKZO91rCR:bqhcmpl) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/Makefile#L31)):*
> ```Makefile
> 	clang-format-11 -i $@
> 
> pythonformat: $(PYTHON_FILES)
> ```

maybe shorter - `pyformat` (?)
___
*[run_benchmark.py, line 4 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKCGBH22SlJgfMrryz:-MTKCGBH22SlJgfMrrz-:b-t7b5cj) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L4)):*
> ```Python
> #
> # SPDX-License-Identifier: Apache-2.0
> # Copyright 2021, Intel Corporation
> ```

`2020-2021`
___
*[run_benchmark.py, line 43 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKmShh77Awu6YMAbgQ:-MTKmShh77Awu6YMAbgR:b6mvktl) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L43)):*
> ```Python
> 
>     def checkout(self):
>         self.logger.info(f"Checking out commit: {self.commit}")
> ```

isn't it good to have in logs also rev-parse'd commit? instead of just "HEAD"
___
*[run_benchmark.py, line 150 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKHv_K-CXb3FYYoOSh:-MTKHv_K-CXb3FYYoOSi:bl1goaq) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L150)):*
> ```Python
>         params_list = [f"{key}={benchmark_params[key]}" for key in benchmark_params]
> 
>         numa_setings = []
> ```

`..settings`
___
*[run_benchmark.py, line 151 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKGz-a0JNvvHDKKP7x:-MTKGz-b4r9Ea_tjXuwA:b-t87nxu) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L151)):*
> ```Python
> 
>         numa_setings = []
>         if "NUMACTL_CPUBIND" in env:
> ```

this name doesn't suggests it should be a path
___
*[run_benchmark.py, line 153 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKHf9Y-f-7jTNpvIqc:-MTKHf9Z2SbB9-RVXwp6:b-dw8msf) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L153)):*
> ```Python
>         if "NUMACTL_CPUBIND" in env:
>             cpubind_path = env["NUMACTL_CPUBIND"]
>             numa_setings = ["numactl", f"--cpubind={cpubind_path}"]
> ```

FYI, I'm guessing not all numactl accepts it:
`libnuma: Warning: unparseable node description `/mnt/pmem/somefile`
and it's a warning, you can possible not see this in the log and not know it was run without numactl proper setting
___
*[run_benchmark.py, line 174 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKiKFJ4omyBAYemqbs:-MTKiKFK5Z8OjYXnn0Ho:b-6orruz) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L174)):*
> ```Python
>         db_path = benchmark_params["--db"]
>         self.logger.info(f"remove {db_path}")
>         os.remove(db_path)
> ```

os.remove? u sure?
___
*[bench_scenarios/basic_build.json, line 15 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKF4n9D8XBTpI3Osl-:-MTKF4nA8yCtWCVpx_UN:blpdfle) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/bench_scenarios/basic_build.json#L15)):*
> ```JSON
>             "-DENGINE_CSMAP=1",
>             "-DENGINE_RADIX=1",
>             "-DENGINE_STREE=1",
> ```

\+robinhood

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: all files reviewed, 11 unresolved discussions (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTLK0JP42YbZg0dR5E5:-MTLK0JQCnPTstPy-oyq:b-roo9vm) (no related file):*
few misspells in the commit messages:
- 'Fortunetely ' -> Fortunately
- 'for some reason contain' -> 'for some reason contains'
- 'build and benchmark configuration' -> 'build and benchmark configurations'
- 'postporcessing' -> 'postprocessing'

---
___
*[Dockerfile.debian-testing, line 4 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKC7pM2IdZ6vZfehVn:-MTLIz8f9bPGCIB1eHwC:bus3cuc) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/Dockerfile.debian-testing#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

why switch from Ubuntu to Debian?
</blockquote></details>

ok, I didn't read the commit message, mea culpa... but anyway, you say "..it contains libpmemobj-dev > 1.8" - we're requiring now on pmemkv master >= 1.9.2
___
*[run_benchmark.py, line 31 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTLIEMD04gDnIg5SQkf:-MTLIEMD04gDnIg5SQkg:b-h6wpj9) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L31)):*
> ```Python
>         self.logger = logging.getLogger(type(self).__name__)
> 
>         self.directory = tempfile.TemporaryDirectory()
> ```

can you built-in the repo name into the generated dirname?

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: all files reviewed, 12 unresolved discussions (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MT_K9_lDkMjjhvYQiTK:-MT_K9_lDkMjjhvYQiTL:b-2fego9) (no related file):*
Wait for #58 

---

**Review by KFilipek — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: all files reviewed, 12 unresolved discussions (waiting on @karczex)

___
*[run_benchmark.py, line 153 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKHf9Y-f-7jTNpvIqc:-MTfv-9O17PsoabNwG-G:b-gu6ptk) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L153)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

FYI, I'm guessing not all numactl accepts it:
`libnuma: Warning: unparseable node description `/mnt/pmem/somefile`
and it's a warning, you can possible not see this in the log and not know it was run without numactl proper setting
</blockquote></details>

AFAIK cpubind takes list of core id's. Good to take care about HT cores

**Comment by karczex** [comment]
___
*[Makefile, line 31 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKC01a3PSTKZO91rCQ:-MTLTeQ48eeV0gJrdmu7:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/Makefile#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe shorter - `pyformat` (?)
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[run_benchmark.py, line 4 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKCGBH22SlJgfMrryz:-MTLTerPEpxq5CabLdzs:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L4)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`2020-2021`
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[run_benchmark.py, line 31 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTLIEMD04gDnIg5SQkf:-MTpF_qE4bU6473DLqla:b-e2gada) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L31)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

can you built-in the repo name into the generated dirname?
</blockquote></details>

Git repo itself doesn't contain it's name. But I agree, the meaningful name for this directory may be good. 
I used sanitized url as prefix. 
Done... I suppose :)

**Comment by karczex** [comment]
___
*[run_benchmark.py, line 150 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKHv_K-CXb3FYYoOSh:-MT_DAGM4vyMv_cMh9op:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L150)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

`..settings`
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[run_benchmark.py, line 151 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKGz-a0JNvvHDKKP7x:-MT_Ct-J6KsPECDx5b-5:b-t0hljb) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L151)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this name doesn't suggests it should be a path
</blockquote></details>

It doesn't have to be path.

**Comment by karczex** [comment]
___
*[run_benchmark.py, line 174 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKiKFJ4omyBAYemqbs:-MTpJ3ztCVsT6-Jxy2Xz:b-expd00) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L174)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

os.remove? u sure?
</blockquote></details>

Good catch :) 
Done.

**Comment by karczex** [comment]
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MT_K9_lDkMjjhvYQiTK:-MTp64vx3DNJ6AoDSd2O:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Wait for #58 
</blockquote></details>

Done.

---

**Comment by karczex** [comment]
*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTLK0JP42YbZg0dR5E5:-MTpLnUE76JNvWOf0XGH:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

few misspells in the commit messages:
- 'Fortunetely ' -> Fortunately
- 'for some reason contain' -> 'for some reason contains'
- 'build and benchmark configuration' -> 'build and benchmark configurations'
- 'postporcessing' -> 'postprocessing'
</blockquote></details>

Done.

---

**Comment by karczex** [comment]
___
*[run_benchmark.py, line 43 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKmShh77Awu6YMAbgQ:-MTpKf9bDCDT415fgjvT:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L43)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

isn't it good to have in logs also rev-parse'd commit? instead of just "HEAD"
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[bench_scenarios/basic_build.json, line 15 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKF4n9D8XBTpI3Osl-:-MT_9q7wAM0QEoGFgSzM:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/bench_scenarios/basic_build.json#L15)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+robinhood
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[bench_scenarios/generate_basic_scope.py, line 45 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MT5xN1-3h5YeAjOz_ER:-MT_CEiJAMBXBcCCY1jM:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/bench_scenarios/generate_basic_scope.py#L45)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

maybe a parameter?
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[bench_scenarios/generate_basic_scope.py, line 49 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MT5x16e9ywFuZeKxMH0:-MT_A0vKCtaPhuv7IPpH:bw29ygr) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/bench_scenarios/generate_basic_scope.py#L49)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

This will work for obj based engines but what about memkind based ones? They expect path to directory so dirname will return something like "/mnt"
</blockquote></details>

This is generator for obj-based engines. I changed file name.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 6 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: all files reviewed, 7 unresolved discussions (waiting on @igchor and @karczex)

___
*[Dockerfile, line 19 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTpkgT41u5h_69dIRHk:-MTpkgT41u5h_69dIRHl:b-34j2d5) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dc3ee9a21776ee4785a549543ccecadbd29e0b42/Dockerfile#L19)):*
> ```Dockerfile
> 	python3-pytest \
> 	python3-jsonschema \
> 	python3-pip\
> ```

I'm guessing it's properly parsed, but pls add a space before ` \`
___
*[run_benchmark.py, line 151 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTKGz-a0JNvvHDKKP7x:-MTpjP7BE0olzIC-s5PE:b-j6cs8z) ([raw file](https://github.com/pmem/pmemkv-bench/blob/120c10335318e3d76ffa256b2756cadec7a3afea/run_benchmark.py#L151)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It doesn't have to be path. 
</blockquote></details>

right, I was biased ;)
___
*[run_benchmark.py, line 177 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTpk_-SB6kYphqb3OzA:-MTpk_-SB6kYphqb3OzB:b-j0t1fe) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dc3ee9a21776ee4785a549543ccecadbd29e0b42/run_benchmark.py#L177)):*
> ```Python
>     def cleanup(self, benchmark_params):
>         db_path = benchmark_params["--db"]
>         self.logger.info(f"remove {db_path}")
> ```

update the log info, perhaps, too
___
*[tests/test.py, line 1 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTpmyPW0Zmcx2gmEgVM:-MTpmyPW0Zmcx2gmEgVN:brhxdf9) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dc3ee9a21776ee4785a549543ccecadbd29e0b42/tests/test.py#L1)):*
> ```Python
> import os, sys
> ```

\+ license
___
*[tests/test.py, line 29 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTpnJvB9gmiIAHwjjXH:-MTpnJvB9gmiIAHwjjXI:bpkjb69) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dc3ee9a21776ee4785a549543ccecadbd29e0b42/tests/test.py#L29)):*
> ```Python
> def test_json():
>     """Basic integration test for run_benchmark.py. It runs full
>     benchmarking process for arbitrary chosen parameters.
> ```

`arbitrary` -> `arbitrarily`
___
*[bench_scenarios/generate_obj_based_scope.py, line 5 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTpmiMW2H_RFAlXbzJp:-MTpmiMW2H_RFAlXbzJq:b-387dwl) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dc3ee9a21776ee4785a549543ccecadbd29e0b42/bench_scenarios/generate_obj_based_scope.py#L5)):*
> ```Python
> # SPDX-License-Identifier: Apache-2.0
> # Copyright 2021, Intel Corporation
> ```

\+ short description, along with info it can be run as a standalone application (as you described in the commit msg)

**Review by KFilipek — COMMENTED** [review]
> Reviewed 5 of 8 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: all files reviewed, 8 unresolved discussions (waiting on @igchor and @karczex)

___
*[run_benchmark.py, line 157 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTq5VMJ3UnTAfZkyT3G:-MTq5VMJ3UnTAfZkyT3H:b-5ldwsl) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dc3ee9a21776ee4785a549543ccecadbd29e0b42/run_benchmark.py#L157)):*
> ```Python
>         if "NUMACTL_CPUBIND" in env:
>             cpubind = env["NUMACTL_CPUBIND"]
>             numa_settings = ["numactl", f"--cpubind={cpubind}"]
> ```

We can also use membind, it can make difference when operating on DRAM.
--membind

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 4 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor and @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTt_YKM5ljnq7jlYuKg:-MTt_YKM5ljnq7jlYuKh:bn85grl) (no related file):*
ref/fixes? #45

---
___
*[bench_scenarios/generate_obj_based_scope.py, line 6 at r5](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTtZuxw8OYk79RWo9uf:-MTtZuxxCOzByhFPRtMV:b-7o41j3) ([raw file](https://github.com/pmem/pmemkv-bench/blob/a1d4e0ef99f6ec5c034f6843856fd4e7fe1136d6/bench_scenarios/generate_obj_based_scope.py#L6)):*
> ```Python
> # Copyright 2021, Intel Corporation
> 
> # This script implements generate() method, which may be invoked by run_becnhmark.py directly,
> ```

`_benchmark` (misspell)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: all files reviewed, 5 unresolved discussions (waiting on @igchor, @karczex, and @KFilipek)

___
*[run_benchmark.py, line 157 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTq5VMJ3UnTAfZkyT3G:-MTt-8eO4kEpLsOt50oP:bppj2d8) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dc3ee9a21776ee4785a549543ccecadbd29e0b42/run_benchmark.py#L157)):*
<details><summary><i>Previously, KFilipek (Krzysztof Filipek) wrote…</i></summary><blockquote>

We can also use membind, it can make difference when operating on DRAM.
--membind
</blockquote></details>

In general it would be good to add separate configuration part for numactl and perf. In this PR I would like to support only cpubind.

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @KFilipek)

**Review by igchor — APPROVED** [review]
:lgtm:

> Reviewed 1 of 4 files at r5.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-:-MTtxsxM54LZzLD8dCKX:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @KFilipek)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 2 of 4 files at r5, 1 of 1 files at r6.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-:-MTtyYd-A_IT7RXT-dbC:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

___
*[run_benchmark.py, line 157 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/55#-MTq5VMJ3UnTAfZkyT3G:-MTtyQJt-C_rp5ZifNOV:bw2jv4c) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dc3ee9a21776ee4785a549543ccecadbd29e0b42/run_benchmark.py#L157)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

In general it would be good to add separate configuration part for numactl and perf. In this PR I would like to support only cpubind. 
</blockquote></details>

Created :)

**Pull request merged**
