### PR TITLE
bench: Fix compilation

### LINKED ISSUE #11: Hi, there is a complie error to build
Hi, there is a complie error
i use ubuntu 18.04
and i complie pmemkv successfully, but i can't complie this tool

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
After recent API changes in pmemkv benchmark building is not working.

Fixes #11

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/12)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/12)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 621 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/12#-Lhf0rb_3GN0uSrfigxL:-Lhf0rbaA6h0-3UR3RPp:b-vjp56h) ([raw file](https://github.com/pmem/pmemkv-tools/blob/02b3e5d34e90df699cc710032051764b37eea3a7/bench/db_bench.cc#L621)):*
> ```cpp
>         auto s = kv_->open("stree", cfg);
> 
>         if (kv_ == nullptr) {
> ```

please check if s == status::OK

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/12)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[bench/db_bench.cc, line 621 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/12#-Lhf0rb_3GN0uSrfigxL:-Lhjg6VS69zjxJEUm-zu:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/02b3e5d34e90df699cc710032051764b37eea3a7/bench/db_bench.cc#L621)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

please check if s == status::OK
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/12)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 621 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/12#-Lhf0rb_3GN0uSrfigxL:-Lht4hl5CQVcNk5u6c9Y:b22z3gg) ([raw file](https://github.com/pmem/pmemkv-tools/blob/02b3e5d34e90df699cc710032051764b37eea3a7/bench/db_bench.cc#L621)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

I think now the logic is reversed. Status::ok means everything succeded so it should rather be`if (s != status::OK)`

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/12)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[bench/db_bench.cc, line 621 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/12#-Lhf0rb_3GN0uSrfigxL:-LhtNGw49s2wd0EXHlTi:b-h9mg4e) ([raw file](https://github.com/pmem/pmemkv-tools/blob/02b3e5d34e90df699cc710032051764b37eea3a7/bench/db_bench.cc#L621)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I think now the logic is reversed. Status::ok means everything succeded so it should rather be`if (s != status::OK)`
</blockquote></details>

omg, of course, done

**Review by igchor — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/12#-:-LhtjAhe3JvXo7BCyvvR:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Review by szyrom — APPROVED** [review]
if compiles - :lgtm: :)

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/12#-:-Li7P0ZI2Vn0bZE5YtRR:bh6g4y6)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
