### PR TITLE
Remove examples from pmemkv-tools

### PR DESCRIPTION
**Pull request by annamarcink**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/22)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 7 of 7 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/22)* status: all files reviewed, 1 unresolved discussion (waiting on @annamarcink)

___
*[README.md, line 113 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/22#-LlC6s449_myl0xlpXfb:-LlC6s449_myl0xlpXfc:bw7ul89) ([raw file](https://github.com/pmem/pmemkv-tools/blob/184c0f65ebb31c4a24a61148ea55f80efe41c29c/README.md#L113)):*
> ```Markdown
> 
> Examples are in individual repos:
> <ul>
> ```

1. you can use list in "md" style instead of "html" style (\* bullet_point)
2. you can use links in "md" style as well (\(description\)\[url\])
3. please add cpp and c examples URLs as well

**Review by annamarcink — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/22)* status: 6 of 7 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[README.md, line 113 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/22#-LlC6s449_myl0xlpXfb:-LlCOeZF74bbE9zVAiY5:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/184c0f65ebb31c4a24a61148ea55f80efe41c29c/README.md#L113)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

1. you can use list in "md" style instead of "html" style (\* bullet_point)
2. you can use links in "md" style as well (\(description\)\[url\])
3. please add cpp and c examples URLs as well
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/22#-:-LlCSiVxApol7t3iVI-3:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Comment by lukaszstolarczuk** [comment]
can you please remove also Python example

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 3 of 3 files at r3.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/22)* status: all files reviewed, 1 unresolved discussion (waiting on @annamarcink)

___
*[Makefile, line 41 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/22#-Lmdxl_j9Y0KccotSgMW:-Lmdxl_j9Y0KccotSgMX:b-h8zxjv) ([raw file](https://github.com/pmem/pmemkv-tools/blob/d36d74d74a09786c0386c3462053298ee3cfa553/Makefile#L41)):*
> ```Makefile
> 	cd .. && $(MAKE) reset
> 
> baseline_python: reset
> ```

this one stays where it is ;)

**Review by annamarcink — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/22)* status: 7 of 8 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[Makefile, line 41 at r3](https://reviewable.io/reviews/pmem/pmemkv-tools/22#-Lmdxl_j9Y0KccotSgMW:-LmdzAvK7aYbVlqI5No9:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/d36d74d74a09786c0386c3462053298ee3cfa553/Makefile#L41)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this one stays where it is ;)
</blockquote></details>

Done.

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/22)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
