### PR TITLE
Various fixes (part 2)

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
Update Makefile to use 'KV_BENCH_TEST_PATH' env var, not just clean some hardcoded paths - if our tests are run with custom test path they won't work, since we don't clean the testing path before the next test and kv.open() fails.

\+ few minor fixes, i.a.:
- fix error messages,
- update comments in bench.cc to C-style,
- get rid of dead code.

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
> Reviewed 4 of 4 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 621 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MWz8rJH5GLka64uI5uj:-MWz8rJH5GLka64uI5uk:b-iblq1s) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dd0d838cab2e934d467a96ddcfb47dceaf632056/bench/db_bench.cc#L621)):*
> ```
> SharedState
> ```
This will not work as intended

**Review by KFilipek — COMMENTED** [review]
"+ few minor fixes."
What fixes?

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-:-MWzFKW_-eGARzXgsoDQ:bm4edts)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
pls see commits' messages

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-:-MX0qGXv91ncWE6AiUyB:bczsq92)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 816 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MX1KxGy-LVNvk21xMcj:-MX1KxGy-LVNvk21xMck:b1pyo4c) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dd0d838cab2e934d467a96ddcfb47dceaf632056/bench/db_bench.cc#L816)):*
> ```cpp
> 				bytes += value_size_ + key.size();
> 				if (s != pmem::kv::status::OK) {
> 					fprintf(stdout, "Out of space at key %i\n", i);
> ```

this isn't true for e.g. robinhood engine and wrong key size - we'll get InvalidArgument - should we check it explicitly here...?

**Review by igchor — APPROVED** [review]
> Reviewed 2 of 4 files at r1, 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 816 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MX1KxGy-LVNvk21xMcj:-MXC2giLBuSxzGolBlvc:b-l9d75c) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dd0d838cab2e934d467a96ddcfb47dceaf632056/bench/db_bench.cc#L816)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

this isn't true for e.g. robinhood engine and wrong key size - we'll get InvalidArgument - should we check it explicitly here...?
</blockquote></details>

what could probably do std::cout << s << " " << db::errormsg() << std::endl;

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[bench/db_bench.cc, line 816 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MX1KxGy-LVNvk21xMcj:-MXC5oZx326nEqA-h5Y2:b-uqzgy3) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dd0d838cab2e934d467a96ddcfb47dceaf632056/bench/db_bench.cc#L816)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

what could probably do std::cout << s << " " << db::errormsg() << std::endl;
</blockquote></details>

if we use `<< s` will set the min. required pmemkv's version to 1.3.
I guess it's acceptable...?

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-:-MXCKDx_5I2tZ4fI50Ss:bnfp4nl)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @igchor and @KFilipek)

___
*[bench/db_bench.cc, line 816 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MX1KxGy-LVNvk21xMcj:-MXgyOyiBNvacbOXpaS5:bijtjfa) ([raw file](https://github.com/pmem/pmemkv-bench/blob/dd0d838cab2e934d467a96ddcfb47dceaf632056/bench/db_bench.cc#L816)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

if we use `<< s` will set the min. required pmemkv's version to 1.3.
I guess it's acceptable...?
</blockquote></details>

as discussed - we can make it just an int - it should be understandable and will not set min. pmemkv's version
___
*[bench/db_bench.cc, line 202 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MXgy171936-6NX8hidt:-MXgy171936-6NX8hidu:b-8l624d) ([raw file](https://github.com/pmem/pmemkv-bench/blob/e2f772cc89b8821277da7a111b6ebad9545687b8/bench/db_bench.cc#L202)):*
> ```cpp
> 	int id = 0;
> 	std::vector<hist> histograms;
> 	CSV<int> csv = CSV<int>("sequence_id");
> ```

the `id` name is a bit misleading - we can change this to provide us with more useful name... Other propositions:
- order_id
- seq_id
- benchmark_sequence
- ...

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)* status: 4 of 5 files reviewed, 3 unresolved discussions (waiting on @igchor, @KFilipek, and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 824 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MXhT5qj2WocqBe-FJiv:-MXhT5qk5lSUVvT3sqLh:b-jwzxhi) ([raw file](https://github.com/pmem/pmemkv-bench/blob/e2f772cc89b8821277da7a111b6ebad9545687b8/bench/db_bench.cc#L824)):*
> ```cpp
> 			thread->stats.FinishedSingleOp();
> 			if (s != pmem::kv::status::OK) {
> 				fprintf(stderr, "Commit failed at batch %i\nError: %s\n", n / batch_size,
> ```

Instead of this `fprintf` with following `exit(1)`, you probably should throw `std::runtime_error`, so you get properly closed pool at the end.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[bench/db_bench.cc, line 824 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MXhT5qj2WocqBe-FJiv:-MXkVLXuEBDkyaH0FCSY:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/e2f772cc89b8821277da7a111b6ebad9545687b8/bench/db_bench.cc#L824)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Instead of this `fprintf` with following `exit(1)`, you probably should throw `std::runtime_error`, so you get properly closed pool at the end. 
</blockquote></details>

Done.

**Comment by karczex** [comment]
___
*[bench/db_bench.cc, line 824 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MXhT5qj2WocqBe-FJiv:-MXlrOcw8hvBVbN19cZM:bvab2au) ([raw file](https://github.com/pmem/pmemkv-bench/blob/e2f772cc89b8821277da7a111b6ebad9545687b8/bench/db_bench.cc#L824)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

Done.
</blockquote></details>

you may probably also move whole this error message to runtime_error.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[bench/db_bench.cc, line 824 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MXhT5qj2WocqBe-FJiv:-MXpvmujDs5XcCQ5CH2u:b-fab9vu) ([raw file](https://github.com/pmem/pmemkv-bench/blob/e2f772cc89b8821277da7a111b6ebad9545687b8/bench/db_bench.cc#L824)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

you may probably also move whole this error message to runtime_error. 
</blockquote></details>

not sure if the best possible way, but done.

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @karczex and @KFilipek)

___
*[bench/db_bench.cc, line 824 at r3](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MXhT5qj2WocqBe-FJiv:-MY50eQT92lL2QEovH7G:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/e2f772cc89b8821277da7a111b6ebad9545687b8/bench/db_bench.cc#L824)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

not sure if the best possible way, but done.
</blockquote></details>

Done.

**Review by igchor — APPROVED** [review]
> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)* status: all files reviewed, 3 unresolved discussions (waiting on @karczex and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 822 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYERkTl46oUDlck3sf_:-MYERkTl46oUDlck3sfa:b-xjxum7) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L822)):*
> ```cpp
> 					throw std::runtime_error(
> 						"Put error for " + std::to_string(i) + "-th key: '" +
> 						std::string(key.ToString().c_str()) +
> ```

key.ToString()
___
*[bench/db_bench.cc, line 824 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYERczsESwW70MzKHBh:-MYERczsESwW70MzKHBi:b-caxgxe) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L824)):*
> ```cpp
> 						std::string(key.ToString().c_str()) +
> 						"' (pmemkv status: " + std::to_string(int(s)) + ", error: " +
> 						std::string(pmem::kv::errormsg().c_str()) + ")");
> ```

`std::string(pmem::kv::errormsg().c_str())` == `pmem::kv::errormsg()`
___
*[bench/db_bench.cc, line 832 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYERLVo1cqBdoYm1lzt:-MYERLVp2xq0XyqE5pmH:b-caxgxe) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L832)):*
> ```cpp
> 				throw std::runtime_error(
> 					"Commit failed at batch " + std::to_string(n / batch_size) +
> 					"\nError: " + std::string(pmem::kv::errormsg().c_str()));
> ```

`std::string(pmem::kv::errormsg().c_str())` == `pmem::kv::errormsg()`
___
*[bench/db_bench.cc, line 948 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYERt2aD1Q4YYaaeMg0:-MYERt2aD1Q4YYaaeMg1:b3kqx) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L948)):*
> ```cpp
> 			if (s != pmem::kv::status::OK) {
> 				throw std::runtime_error(
> 					"Put error for key '" + std::string(key.ToString().c_str()) +
> ```

.
___
*[bench/db_bench.cc, line 951 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYERrnJ2fbWBN6UKY_2:-MYERrnJ2fbWBN6UKY_3:b3kqx) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L951)):*
> ```cpp
> 					"' (pmemkv status: " + std::to_string(int(s)) +
> 					", error: " + std::string(pmem::kv::errormsg().c_str()) + ")");
> 			}
> ```

.
___
*[bench/db_bench.cc, line 1009 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYERxU-CemK93cqSWAk:-MYERxU-CemK93cqSWAl:bs8xrcv) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L1009)):*
> ```cpp
> 					kv_->put(key.ToString(), gen.Generate(value_size_).ToString());
> 				if (s != pmem::kv::status::OK) {
> 					throw std::runtime_error(
> ```

Maybe put this in a function? It's used quite a lot.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)* status: all files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 786 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYE8sWH1S9s-TWG9-aX:-MYE8sWH1S9s-TWG9-aY:bpqwk9h) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L786)):*
> ```cpp
> 				"Cannot start engine (%s) for path (%s) with %i GB capacity\nError: %s",
> 				engine, FLAGS_db, FLAGS_db_size_in_gb, pmem::kv::errormsg().c_str());
> 			exit(-42);
> ```

exception?

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69)* status: 4 of 5 files reviewed, 2 unresolved discussions (waiting on @igchor and @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYFJ2dDBOxbCOqcmzEQ:-MYFJ2dDBOxbCOqcmzER:bcl7fnw) (no related file):*
right now the error looks like this:

```
Running fillseq
terminate called after throwing an instance of 'std::runtime_error'
  what():  Put error for 294-th key: '&''0x1''0x0''0x0''0x0''0x0''0x0''0x0' (pmemkv status: 0, error: '')
```

// corner case (where value is `'`) looks weird, but it's understandable I hope:
` what():  Put error for 295-th key: ''''0x1''0x0''0x0''0x0''0x0''0x0''0x0' (pmemkv status: 0, error: '')`

---
___
*[bench/db_bench.cc, line 786 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYE8sWH1S9s-TWG9-aX:-MYFIQyj8P8a-qZXH4mZ:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L786)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

exception?
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 822 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYERkTl46oUDlck3sf_:-MYFISem6LO2pbyMt_di:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L822)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

key.ToString()
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 824 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYERczsESwW70MzKHBh:-MYFIS2W-2FQ1OSwPuwj:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L824)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`std::string(pmem::kv::errormsg().c_str())` == `pmem::kv::errormsg()`
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 832 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYERLVo1cqBdoYm1lzt:-MYFITGE199RYOHkI8-a:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L832)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

`std::string(pmem::kv::errormsg().c_str())` == `pmem::kv::errormsg()`
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 948 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYERt2aD1Q4YYaaeMg0:-MYFIUqC8O4mIsS2Wb7N:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L948)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 951 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYERrnJ2fbWBN6UKY_2:-MYFIUFk5Eerh0Ww5KvY:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L951)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

.
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 1009 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-MYERxU-CemK93cqSWAk:-MYFINE93Q7gzXfK_am1:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/1a43edbb72ff4f972807fea2bd3c46f4b941524d/bench/db_bench.cc#L1009)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Maybe put this in a function? It's used quite a lot.
</blockquote></details>

Done.

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-:-MYJOW4J4fuUORI9WiAG:bnfp4nl)* status: 4 of 5 files reviewed, 1 unresolved discussion (waiting on @igchor and @karczex)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/69#-:-MYJlKRD5gFILoD9DEXL:bnfp4nl)* status: 4 of 5 files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
