### PR TITLE
Various fixes

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/65)

### CODE REVIEW

**Review by KFilipek — COMMENTED** [review]
I moved through the changes and I believe you can squash some commits, but is not must have.
Generally: :lgtm:

> Reviewed 6 of 6 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/65#-:-MW4-9Bi4QUW97qqcRbt:bggg9w8)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Comment by lukaszstolarczuk** [comment]
As discussed on the meeting `print_histogram` flag is no longer necessary. I've dropped that commit.

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/65)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @KFilipek and @lukaszstolarczuk)

___
*[bench_scenarios/generate_obj_based_scope.py, line 58 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/65#-MW47bXF8_s7wtTDpT-v:-MW47bXGBr2xh0HuOFWj:buzn1la) ([raw file](https://github.com/pmem/pmemkv-bench/blob/87eceb9159513fc15668f3b7dbc1a234c5af75f9/bench_scenarios/generate_obj_based_scope.py#L58)):*
> ```Python
>                 "--benchmarks": f"{benchmark[0]}",
>                 "--value_size": f"{benchmark[1]}",
>                 "--key_size": f"{benchmark[1]}",
> ```

It you want to do such change, you may want to make key_size separate field (change in single_threaded_engines() and concurrent engines())

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/65)* status: 5 of 6 files reviewed, 1 unresolved discussion (waiting on @karczex and @KFilipek)

___
*[bench_scenarios/generate_obj_based_scope.py, line 58 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/65#-MW47bXF8_s7wtTDpT-v:-MW4HPr1-b2hIw-gWU2h:b-ux197j) ([raw file](https://github.com/pmem/pmemkv-bench/blob/87eceb9159513fc15668f3b7dbc1a234c5af75f9/bench_scenarios/generate_obj_based_scope.py#L58)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

It you want to do such change, you may want to make key_size separate field (change in single_threaded_engines() and concurrent engines())
</blockquote></details>

Not sure if this is required - I mean, before my change we were using the default value for `key_size`, and now we'll be using the same size as the `value_size` - so we just require in both of the mentioned methods just one field - `size` (as it is right now...)

If we change that, and use two different fields for sizes, we'll have even bigger number of configs (as a result of `itertools.product()` ;) )

**Comment by lukaszstolarczuk** [comment]
as discussed offline, set arbitrary key size to 8 (in scenarios and in bench code)

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/65#-:-MWSwvQ98XVPFHUQ_WZn:bnfp4nl)* status: 2 of 6 files reviewed, all discussions resolved (waiting on @KFilipek)

**Pull request merged**
