### PR TITLE
Add basic dockerfile

### PR DESCRIPTION
**Pull request by karczex**
For now use all depenencies from Ubuntu repository. I hope it will stay like
this in the future.
This image may be used in CI

---
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/42)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/42)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @karczex)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/42#-MO7-petEFeFr-6yhNY9:-MO7-petEFeFr-6yhNYA:b-xq55qq) (no related file):*
maybe rename to use the naming convention as in our other repos? `Dockerfile.ubuntu-20.04`

---
___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/42#-MO7-bSID3hzbTmw015j:-MO7-bSJBhKExgR27Tgg:bfojdol) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9946f40839d863e45e81f88b6122a42948451e07/Dockerfile#L1)):*
> ```Dockerfile
> # SPDX-License-Identifier: Apache-2.0
> ```

hmm this repo is on Apache license...? not BSD?
___
*[Dockerfile, line 12 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/42#-MO7-m6lAFJjb5QE5RD4:-MO7-m6lAFJjb5QE5RD5:ba5n151) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9946f40839d863e45e81f88b6122a42948451e07/Dockerfile#L12)):*
> ```Dockerfile
> 	make \
> 	g++ \
> 	pkg-config \
> ```

what about pmemkv?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/42)* status: 0 of 1 files reviewed, 4 unresolved discussions (waiting on @karczex)

___
*[Dockerfile, line 9 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/42#-MOApxIr3c_RUi-nJVsu:-MOApxIs2Mvo8HDW5a4g:b-wna8ox) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9946f40839d863e45e81f88b6122a42948451e07/Dockerfile#L9)):*
> ```Dockerfile
> RUN apt update && \
> 	DEBIAN_FRONTEND=noninteractive apt install -y --no-install-recommends \
> 	libpmemkv-dev \
> ```

do we really want to install pmemkv from packages?

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/42)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

___
*[Dockerfile, line 9 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/42#-MOApxIr3c_RUi-nJVsu:-MOAzqUl7ZYesIVINpbH:b-eswcou) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9946f40839d863e45e81f88b6122a42948451e07/Dockerfile#L9)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

do we really want to install pmemkv from packages?
</blockquote></details>

for some testing, why not... if we use master version of pmemkv then it also won't be the latest version (we'll have to update the install-pmemkv.sh script often)

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/42)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor and @karczex)

___
*[Dockerfile, line 9 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/42#-MOApxIr3c_RUi-nJVsu:-MOB-H8HAD34UWSF0nx_:bhedzjg) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9946f40839d863e45e81f88b6122a42948451e07/Dockerfile#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

for some testing, why not... if we use master version of pmemkv then it also won't be the latest version (we'll have to update the install-pmemkv.sh script often)
</blockquote></details>

hmm ok, unless we'll force to rebuild every time and use moving target: `git checkout master`

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/42)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor, @karczex, and @lukaszstolarczuk)

___
*[Dockerfile, line 1 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/42#-MO7-bSID3hzbTmw015j:-MOB3PcK6djwLlq4bnyE:bb7sa0c) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9946f40839d863e45e81f88b6122a42948451e07/Dockerfile#L1)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm this repo is on Apache license...? not BSD?
</blockquote></details>

yes.
___
*[Dockerfile, line 9 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/42#-MOApxIr3c_RUi-nJVsu:-MOB4EPmADrGg-Y9Pwj5:bcdw5p5) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9946f40839d863e45e81f88b6122a42948451e07/Dockerfile#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

hmm ok, unless we'll force to rebuild every time and use moving target: `git checkout master`
</blockquote></details>

Purpose of this image, is to run very basic smoke tests on gha. In fact testing of building with version from ubuntu repo is good idea itself. 
If we need image with rolling version we should build another one based on image generated in pmemkv CI, which contains installed current master release build in standard path. 
___
*[Dockerfile, line 12 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/42#-MO7-m6lAFJjb5QE5RD4:-MOB3lKZ48zwEuelt3E7:b-33zi9b) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9946f40839d863e45e81f88b6122a42948451e07/Dockerfile#L12)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

what about pmemkv?
</blockquote></details>

it's dependency for libpmemkv-dev. 

```
# apt show libpmemkv-dev
Package: libpmemkv-dev
Version: 1.1-1
Status: install ok installed
Priority: optional
Section: libdevel
Source: pmemkv
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Adam Borowski <kilobyte@angband.pl>
Installed-Size: 81.9 kB
Depends: libpmemkv1 (= 1.1-1)
Homepage: https://github.com/pmem/pmemkv
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: key:value data store for persistent memory
 Pmemkv is a family of key:value stores, developed with persistent memory
 in mind -- yet rather than being tied to a single backing implementation,
 it presents a common interface to a number of engines, both provided by
 pmemkv itself and external.
 .
 This package contains the development headers.
```

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/42)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @igchor and @lukaszstolarczuk)

*[a discussion](https://reviewable.io/reviews/pmem/pmemkv-bench/42#-MO7-petEFeFr-6yhNY9:-MOB8uFe4vF6kAIUfQ85:b-896fix) (no related file):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

maybe rename to use the naming convention as in our other repos? `Dockerfile.ubuntu-20.04`
</blockquote></details>

Done.

---

**Review by lukaszstolarczuk — APPROVED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/42)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[Dockerfile, line 12 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/42#-MO7-m6lAFJjb5QE5RD4:-MOBKrHs1mC5U-nZkB7i:b-bfbgon) ([raw file](https://github.com/pmem/pmemkv-bench/blob/9946f40839d863e45e81f88b6122a42948451e07/Dockerfile#L12)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

it's dependency for libpmemkv-dev. 

```
# apt show libpmemkv-dev
Package: libpmemkv-dev
Version: 1.1-1
Status: install ok installed
Priority: optional
Section: libdevel
Source: pmemkv
Maintainer: Ubuntu Developers <ubuntu-devel-discuss@lists.ubuntu.com>
Original-Maintainer: Adam Borowski <kilobyte@angband.pl>
Installed-Size: 81.9 kB
Depends: libpmemkv1 (= 1.1-1)
Homepage: https://github.com/pmem/pmemkv
Download-Size: unknown
APT-Manual-Installed: yes
APT-Sources: /var/lib/dpkg/status
Description: key:value data store for persistent memory
 Pmemkv is a family of key:value stores, developed with persistent memory
 in mind -- yet rather than being tied to a single backing implementation,
 it presents a common interface to a number of engines, both provided by
 pmemkv itself and external.
 .
 This package contains the development headers.
```
</blockquote></details>

nevermind, I retracted this issue, because I originally thought about libpmemobj-cpp, but then realized it is also a dependency.
:+1:

**Review by igchor — APPROVED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/42)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @karczex)

**Pull request merged**
