### PR TITLE
Implement txfillrandom benchmark

### PR DESCRIPTION
**Pull request by igchor**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/36)

### CODE REVIEW

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/36)* status: all files reviewed, 3 unresolved discussions (waiting on @igchor)

___
*[bench/db_bench.cc, line 9 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/36#-MK_nLZH7iXmc3uuLZc6:-MK_nLZH7iXmc3uuLZc7:b-8mxykc) ([raw file](https://github.com/pmem/pmemkv-tools/blob/bd11c4b358ace21f98c933a0cb9bbed0bb288892/bench/db_bench.cc#L9)):*
> ```cpp
> // (found in the LICENSE file in the root directory).
> 
> // Copyright (c) 2017-2019, Intel Corporation
> ```

-2020
___
*[bench/db_bench.cc, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/36#-MK_mBh8-LPlwH_bDyjZ:-MK_mBh8-LPlwH_bDyj_:b-f36056) ([raw file](https://github.com/pmem/pmemkv-tools/blob/bd11c4b358ace21f98c933a0cb9bbed0bb288892/bench/db_bench.cc#L47)):*
> ```cpp
>         "In other words, 9 gets for every 1 put.) type: int32 default: 90\n"
>         "--tx_size=<integer>        (number of elements to insert in a single tx, there will be"
>         "num/tx_size transactions per thread in total, the last tx might be smaller)\n"
> ```

\+ default value
___
*[bench/db_bench.cc, line 59 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/36#-MK_l6oq71OVw6ary7Oi:-MK_l6oq71OVw6ary7Oj:b-mu6129) ([raw file](https://github.com/pmem/pmemkv-tools/blob/bd11c4b358ace21f98c933a0cb9bbed0bb288892/bench/db_bench.cc#L59)):*
> ```cpp
>         "    readwhilewriting       (1 writer, N threads doing random reads)\n"
>         "    readrandomwriterandom  (N threads doing random-read, random-write)\n"
>         "    txfillrandom           (load N values in random key order transactionally \n";
> ```

add close parenthesis `)`

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/36)* status: 0 of 1 files reviewed, 3 unresolved discussions (waiting on @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 9 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/36#-MK_nLZH7iXmc3uuLZc6:-MOpLDm9DsTe4OG8_u1Q:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/bd11c4b358ace21f98c933a0cb9bbed0bb288892/bench/db_bench.cc#L9)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

-2020
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 47 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/36#-MK_mBh8-LPlwH_bDyjZ:-MOpLP2vBULnF4GpZcGt:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/bd11c4b358ace21f98c933a0cb9bbed0bb288892/bench/db_bench.cc#L47)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

\+ default value
</blockquote></details>

Done.
___
*[bench/db_bench.cc, line 59 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/36#-MK_l6oq71OVw6ary7Oi:-MOpLSTt79pzJoBoDTDU:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/bd11c4b358ace21f98c933a0cb9bbed0bb288892/bench/db_bench.cc#L59)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

add close parenthesis `)` 
</blockquote></details>

Done.

**Comment by lukaszstolarczuk** [comment]
ref. https://github.com/pmem/pmemkv/pull/830

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/36)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[bench/db_bench.cc, line 521 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/36#-MOpajZZDA8RxITCCZ7I:-MOpajZ_BZRlgO7FMoah:b4qwbns) ([raw file](https://github.com/pmem/pmemkv-bench/blob/bd11c4b358ace21f98c933a0cb9bbed0bb288892/bench/db_bench.cc#L521)):*
> ```cpp
>             } else if (name == Slice("readrandomwriterandom")) {
>                 method = &Benchmark::ReadRandomWriteRandom;
>             } else if (name == Slice("txfillrandom")) {
> ```

something went wrong while rebasing? shouldn't this code be still here?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/36)* status: all files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 521 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/36#-MOpajZZDA8RxITCCZ7I:-MR-glAU6aigr0GKqW41:b-896fix) ([raw file](https://github.com/pmem/pmemkv-bench/blob/bd11c4b358ace21f98c933a0cb9bbed0bb288892/bench/db_bench.cc#L521)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

something went wrong while rebasing? shouldn't this code be still here?
</blockquote></details>

Done.

**Review by lukaszstolarczuk — CHANGES_REQUESTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/36)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @igchor and @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 50 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/36#-MR02etAAlk5b8J2Q-Rz:-MR02etBA7iQsrGhx5eg:b-vu5z1f) ([raw file](https://github.com/pmem/pmemkv-bench/blob/6a5200e0f30610d46c0e625aeb7d2ff67c96a4ad/bench/db_bench.cc#L50)):*
> ```cpp
>         "90 means 90% operations out of all reads and writes operations are reads. "
>         "In other words, 9 gets for every 1 put.) type: int32 default: 90\n"
>         "--tx_size=<integer>        (number of elements to insert in a single tx, there will be"
> ```

now we're missing tx_size here, aren't we?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/36)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk)

___
*[bench/db_bench.cc, line 50 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/36#-MR02etAAlk5b8J2Q-Rz:-MRJ_lkX52tMwpBxny93:b1slrmw) ([raw file](https://github.com/pmem/pmemkv-bench/blob/6a5200e0f30610d46c0e625aeb7d2ff67c96a4ad/bench/db_bench.cc#L50)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

now we're missing tx_size here, aren't we?
</blockquote></details>

Done, I hope that the last fix ;d

**Review by lukaszstolarczuk — APPROVED** [review]
:lgtm:

> Reviewed 1 of 1 files at r4.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/36#-:-MRJbC2j3bej8jpDgESl:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

___
*[bench/db_bench.cc, line 50 at r2](https://reviewable.io/reviews/pmem/pmemkv-bench/36#-MR02etAAlk5b8J2Q-Rz:-MRJb9PC5olxLW84E7sn:b-458nvn) ([raw file](https://github.com/pmem/pmemkv-bench/blob/6a5200e0f30610d46c0e625aeb7d2ff67c96a4ad/bench/db_bench.cc#L50)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

Done, I hope that the last fix ;d
</blockquote></details>

Run the benchmark - we'll know ;)

**Review by karczex — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/36)* status: all files reviewed, 1 unresolved discussion (waiting on @igchor)

___
*[bench/db_bench.cc, line 788 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/36#-MRP_u7PEzyXjragHV__:-MRP_u7PEzyXjragHV_a:b660v7q) ([raw file](https://github.com/pmem/pmemkv-bench/blob/06b85f841aac13543aa30d910a557f6727603ed0/bench/db_bench.cc#L788)):*
> ```cpp
> 		pmem::kv::status s;
> 		int64_t bytes = 0;
> 		auto batch_size = std::is_same<Inserter, TxInserter>::value ? tx_size_ : 1;
> ```

Wouldn't be better to add pure virtual base class for Inserter and TxInserter, and add method get_batch_size() to both?

**Review by igchor — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/36)* status: all files reviewed, 1 unresolved discussion (waiting on @karczex)

___
*[bench/db_bench.cc, line 788 at r4](https://reviewable.io/reviews/pmem/pmemkv-bench/36#-MRP_u7PEzyXjragHV__:-MRUewp30YTu7L-18B1k:b-ciup4) ([raw file](https://github.com/pmem/pmemkv-bench/blob/06b85f841aac13543aa30d910a557f6727603ed0/bench/db_bench.cc#L788)):*
<details><summary><i>Previously, karczex (Paweł Karczewski) wrote…</i></summary><blockquote>

Wouldn't be better to add pure virtual base class for Inserter and TxInserter, and add method get_batch_size() to both?  
</blockquote></details>

But then you'd have to dynamically allocate the Inserter and you will still want to have compile-time information about the type (so that put/commit is as fast as possible) so this will probably result in more code, not less

**Review by karczex — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/36#-:-MRVQmgG9MIuw156lhFG:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @igchor)

**Pull request merged**
