### PR TITLE
charts: extend functionalities

### PR DESCRIPTION
**Pull request by lukaszstolarczuk**
- add new parameter to store raw numbers before putting them on charts
- add extra info on the chart (or rather beneath it)

This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/75)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/75)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

___
*[utils/charts/perf_charts.py, line 30 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/75#-Ma8kYRn8wmotaBnJ5TS:-Ma8kYRn8wmotaBnJ5TT:b-gq4tk2) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0ae2cc11446a9e63c0450a099ce6785d6b62d1a5/utils/charts/perf_charts.py#L30)):*
> ```Python
> DEFAULT_CHART_DESCRIPTION = """
> Benchmark: pmemkv-bench<br />
> Platform: Intel Optane PMem on 2S Intel Xeon 8280L Server<br />
> ```

I'm not sure if such info should be present here - there's 100% chance we'll forget to change this ;d

**Review by lukaszstolarczuk — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/75)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @igchor)

___
*[utils/charts/perf_charts.py, line 30 at r1](https://reviewable.io/reviews/pmem/pmemkv-bench/75#-Ma8kYRn8wmotaBnJ5TS:-Ma9HuIJBs-fAyvwb3K6:b2ueton) ([raw file](https://github.com/pmem/pmemkv-bench/blob/0ae2cc11446a9e63c0450a099ce6785d6b62d1a5/utils/charts/perf_charts.py#L30)):*
<details><summary><i>Previously, igchor (Igor Chorążewicz) wrote…</i></summary><blockquote>

I'm not sure if such info should be present here - there's 100% chance we'll forget to change this ;d
</blockquote></details>

for now, I'd change this to something like this... We could actually read this info from some kind of configuration file, or something... but it seems a bit unnecessary work right now.

If we generate charts using this script it can be easily updated with a proper value and for sure we won't send this anywhere with such "XXX" message ;)

**Review by KFilipek — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/75#-:-MahmR0lDq8M_27_HuGv:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by igchor — APPROVED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-bench/75#-:-Mb_l8LU8Ls-CsekKjNa:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Pull request merged**
