### PR TITLE
Fix pmemkv_bench utility to conform new pmemkv API

### PR DESCRIPTION
**Pull request by vinser52**
This change is [Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/16)

### CODE REVIEW

**Review by igchor — COMMENTED** [review]
:lgtm:

> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/16#-:-LiheEiG1OLEfnMcFEnO:bnfp4nl)* status: 0 of 1 files reviewed, all discussions resolved (waiting on @igchor, @lukaszstolarczuk, and @szyrom)

**Review by szyrom — APPROVED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/16)* status: :shipit: complete! all files reviewed, all discussions resolved (waiting on @lukaszstolarczuk)

**Review by lukaszstolarczuk — COMMENTED** [review]
> Reviewed 1 of 1 files at r1.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/16)* status: all files reviewed, 1 unresolved discussion (waiting on @vinser52)

___
*[bench/db_bench.cc, line 636 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/16#-LiiOY9z-4MV6r1jM6tK:-LiiOYA-CQ1JO3RvRmzN:b-sgdak9) ([raw file](https://github.com/pmem/pmemkv-tools/blob/021b43a2e52eea75e436fc4740f267e8edc23c35/bench/db_bench.cc#L636)):*
> ```cpp
>         }
> 
>         pmemkv_config_delete(cfg);
> ```

I believe we don't need this line anymore

**Review by vinser52 — COMMENTED** [review]
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/16)* status: 0 of 1 files reviewed, 1 unresolved discussion (waiting on @lukaszstolarczuk and @szyrom)

___
*[bench/db_bench.cc, line 636 at r1](https://reviewable.io/reviews/pmem/pmemkv-tools/16#-LiiOY9z-4MV6r1jM6tK:-LijAz2i0JVao-a8Ir1W:b-896fix) ([raw file](https://github.com/pmem/pmemkv-tools/blob/021b43a2e52eea75e436fc4740f267e8edc23c35/bench/db_bench.cc#L636)):*
<details><summary><i>Previously, lukaszstolarczuk (Łukasz Stolarczuk) wrote…</i></summary><blockquote>

I believe we don't need this line anymore
</blockquote></details>

Done.

**Review by lukaszstolarczuk — COMMENTED** [review]
:lgtm:

> Reviewed 1 of 1 files at r2.
> *[Reviewable](https://reviewable.io/reviews/pmem/pmemkv-tools/16#-:-LimQPdN1_7gpktl3uH8:bnfp4nl)* status: :shipit: complete! all files reviewed, all discussions resolved

**Pull request merged**
